<a href="https://colab.research.google.com/github/towardsai/ai-tutor-rag-system/blob/main/notebooks/06-Evaluate_RAG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluating Your RAG Pipeline

Our pipeline retrieves chunks and answers questions — but *how well*? In this notebook we measure it, with the two evaluations every RAG system needs: **does the retriever find the right chunk** (hit rate, MRR), and **are the generated answers any good** (faithfulness, relevancy, correctness, judged by an LLM). Along the way we build a synthetic evaluation dataset the safe way — with structured output, so no parsing step can silently corrupt it.

*Model outputs in this notebook were captured in August 2026 with the pinned course models — LLMs evolve, so your outputs and scores may differ slightly. What should stay stable are the patterns and the shape of the results.*

## 🧭 What You'll Learn

- Rebuild a small RAG index with **ChromaDB** and the course `embed()` helper — a real vector database instead of an in-memory DataFrame
- Generate a **synthetic evaluation dataset** of question ↔ chunk pairs, using **structured output** so the questions can never be corrupted by parsing
- The habit that saves eval projects: **eyeball your synthetic data before scoring anything**
- **Hit rate** and **MRR** as ten-line Python functions, swept over different top-k values
- **LLM judges** with typed verdicts: faithfulness (no hallucinations), relevancy (on-topic), and correctness (matches a reference answer)
- Why a judge needs a **stronger model** than the pipeline it grades

## 1. Setup: Environment, Keys, and Providers

The standard course setup cell: pick a chat provider and an embedding provider, and it installs pinned dependencies (in Colab) and loads the matching API keys from Colab Secrets (Colab) or a `.env` file at the repo root (local). Chat and embeddings are independent choices — the course default is Gemini for both. (Anthropic has no embedding API, so embeddings offer Gemini or OpenAI.)

The **model fields are editable dropdowns** (`{allow-input: true}`): pick one of the listed course defaults, or type any newer model ID straight into the box — no code changes needed. (Locally, simply edit the string.)

In [1]:
# ============================================================
# ⚙️ Setup — environment, dependencies, API keys, provider
# ============================================================
import os
import sys

IN_COLAB = "google.colab" in sys.modules

# Pick your model providers (dropdowns in Colab; edit the values locally)
PROVIDER = "gemini"  # @param ["gemini", "openai", "anthropic"]
EMBED_PROVIDER = "gemini"  # @param ["gemini", "openai"]  (Anthropic has no embedding API)

# Pick a model for the selected provider — or TYPE any newer model ID into the
# box (the dropdown is editable thanks to allow-input):
CHAT_MODEL = "gemini-3.5-flash-lite"  # @param ["gemini-3.5-flash-lite", "gpt-5.6-luna", "claude-haiku-4-5"] {allow-input: true}
EMBED_MODEL = "gemini-embedding-001"  # @param ["gemini-embedding-001", "text-embedding-3-small"] {allow-input: true}

_KEY_FOR = {"gemini": "GOOGLE_API_KEY", "openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}
REQUIRED_KEYS = sorted({_KEY_FOR[PROVIDER], _KEY_FOR[EMBED_PROVIDER]})

if IN_COLAB:
    import importlib
    import site
    import subprocess

    # Shared install profile, pinned course-wide (set checked August 3, 2026).
    subprocess.run(
        [
            sys.executable, "-m", "pip", "install", "-q", "-U",
            "google-genai==2.16.0",
            "openai==2.52.1",
            "anthropic==0.120.2",
            "chromadb==1.5.9",
        ],
        check=True,
    )
    importlib.reload(site)  # make newly installed packages importable without a runtime restart

    # In Colab: Secrets tab (🔑 icon in the left sidebar) → Add new secret →
    # name it e.g. GOOGLE_API_KEY, paste the key, and toggle notebook access on.
    from google.colab import userdata

    for key in REQUIRED_KEYS:
        os.environ[key] = userdata.get(key)

if not IN_COLAB:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")

    # Locally: dependencies are installed once from the repo's requirements.
    # Keys live in a .env file at the repo root (never hardcode keys in cells).
    from dotenv import load_dotenv

    load_dotenv()
    missing = [k for k in REQUIRED_KEYS if not os.getenv(k)]
    assert not missing, f"Missing from .env: {missing}"

print(f"✅ Setup complete — {'Colab' if IN_COLAB else 'local'} | chat: {PROVIDER} | embeddings: {EMBED_PROVIDER}")

✅ Setup complete — local | chat: gemini | embeddings: gemini

## 2. The `generate()`, `embed()`, and Judge Helpers

Both provider helpers come from earlier notebooks: `generate()` from the "How To Use LLMs via API" notebook, `embed()` from the Basic RAG notebook. **New here is `JUDGE_MODELS`** — evaluation gives models two different jobs, and they deserve two different roles:

- **The pipeline under test** answers questions with the cheap course default (`gemini-3.5-flash-lite`).
- **The judge** grades those answers. Judging is the harder job — a judge that misses hallucinations is worse than no judge — so where the provider has a stronger affordable model, the judge role gets it: `gemini-3.6-flash` on Gemini. On OpenAI and Anthropic the course defaults (`gpt-5.6-luna`, `claude-haiku-4-5`) serve both roles.

One rule to remember: **never let a weaker model judge a stronger one** — pick your judge at least as capable as the model it grades.

In [2]:
# 📎 generate() was built in the "How To Use LLMs via API" notebook and
#    embed() in the Basic RAG notebook. New here: JUDGE_MODELS — the judge role
#    gets a stronger model where the provider offers one.
from anthropic import Anthropic
from google import genai
from google.genai import types as genai_types
from openai import OpenAI

# Course-standard default models per provider (August 2026)
MODELS = {
    "gemini": "gemini-3.5-flash-lite",
    "openai": "gpt-5.6-luna",
    "anthropic": "claude-haiku-4-5",
}
MODELS[PROVIDER] = CHAT_MODEL  # the setup-cell selection (or typed ID) wins

# The judge role, per provider
JUDGE_MODELS = {
    "gemini": "gemini-3.6-flash",
    "openai": "gpt-5.6-luna",
    "anthropic": "claude-haiku-4-5",
}
JUDGE_MODEL = JUDGE_MODELS[PROVIDER]

EMBED_MODELS = {
    "gemini": "gemini-embedding-001",
    "openai": "text-embedding-3-small",
}
EMBED_MODELS[EMBED_PROVIDER] = EMBED_MODEL  # setup-cell selection (or typed ID) wins
EMBED_DIM = 1536  # same output size for both providers

# Create only the clients we actually need
if "gemini" in (PROVIDER, EMBED_PROVIDER):
    gemini_client = genai.Client()
if "openai" in (PROVIDER, EMBED_PROVIDER):
    openai_client = OpenAI()
if PROVIDER == "anthropic":
    anthropic_client = Anthropic()


def generate(prompt, system=None, model=None):
    """Send one prompt to the selected PROVIDER and return the reply text."""
    if PROVIDER == "gemini":
        response = gemini_client.models.generate_content(
            model=model or MODELS["gemini"],
            contents=prompt,
            config=genai_types.GenerateContentConfig(system_instruction=system),
        )
        return response.text or ""

    if PROVIDER == "openai":
        response = openai_client.responses.create(
            model=model or MODELS["openai"],
            instructions=system,
            input=prompt,
            reasoning={"effort": "none"},
        )
        return response.output_text or ""

    if PROVIDER == "anthropic":
        response = anthropic_client.messages.create(
            model=model or MODELS["anthropic"],
            max_tokens=4096,
            # Anthropic rejects system=None, so only pass it when set
            **({"system": system} if system else {}),
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text or ""

    raise ValueError(f"Unknown PROVIDER: {PROVIDER!r}")


def embed(texts, task="document"):
    """Embed a list of texts with the selected EMBED_PROVIDER.

    Returns one EMBED_DIM-dimensional vector per input text.
    task: "document" for corpus chunks, "query" for questions — retrieval
    models treat the two sides differently.
    """
    if isinstance(texts, str):
        texts = [texts]
    # Embedding models work best on single-line inputs
    texts = [t.replace("\n", " ") for t in texts]

    if EMBED_PROVIDER == "gemini":
        result = gemini_client.models.embed_content(
            model=EMBED_MODELS["gemini"],
            contents=texts,
            config=genai_types.EmbedContentConfig(
                task_type="RETRIEVAL_DOCUMENT" if task == "document" else "RETRIEVAL_QUERY",
                output_dimensionality=EMBED_DIM,
            ),
        )
        return [e.values for e in result.embeddings]

    if EMBED_PROVIDER == "openai":
        result = openai_client.embeddings.create(
            model=EMBED_MODELS["openai"], input=texts, dimensions=EMBED_DIM
        )
        return [d.embedding for d in result.data]

    raise ValueError(f"Unknown EMBED_PROVIDER: {EMBED_PROVIDER!r}")

## 3. Load the Dataset

The same corpus as the previous lessons: a small CSV of Towards AI blog articles about the Llama 2 model family.

In [3]:
import pathlib

import requests

DATA_URL = "https://raw.githubusercontent.com/AlaFalaki/tutorial_notebooks/main/data/mini-llama-articles.csv"
DATA_PATH = pathlib.Path("mini-llama-articles.csv")

if not DATA_PATH.exists():
    DATA_PATH.write_bytes(requests.get(DATA_URL, timeout=30).content)
    print("Downloaded", DATA_PATH)
else:
    print("Already present:", DATA_PATH)

Downloaded mini-llama-articles.csv

## 4. Chunking with Deterministic IDs

We split each article into fixed-size chunks of 2,048 characters (roughly 512 tokens) — the simple chunker from the Basic RAG notebook, at a size that suits retrieval.

The new idea is the **chunk ID**. Our evaluation dataset will store, for every question, the ID of the chunk that answers it — that ID *is* the ground truth. If IDs were random (the usual default), re-running the notebook would assign new IDs to every chunk, and a saved evaluation dataset would point at IDs that no longer exist. So we make IDs **deterministic**: a [SHA-256](https://en.wikipedia.org/wiki/SHA-2) hash of the article number and chunk position. Same data in, same IDs out — on every machine, on every rerun.

In [4]:
import csv
import hashlib


def split_into_chunks(text, chunk_size=2048):
    """Fixed-size character chunks (~512 tokens each)."""
    return [text[i : i + chunk_size] for i in range(0, len(text), chunk_size)]


def chunk_id(article_idx, chunk_idx):
    """Deterministic chunk ID: the same article and position always hash to the same ID."""
    unique_identifier = f"doc_{article_idx}_{chunk_idx}"
    return hashlib.sha256(unique_identifier.encode("utf-8")).hexdigest()


chunks = []
with open(DATA_PATH, mode="r", encoding="utf-8") as file:
    csv_reader = csv.reader(file)
    next(csv_reader)  # skip the header row
    for article_idx, row in enumerate(csv_reader):
        title, content, url = row[0], row[1], row[2]
        for chunk_idx, text in enumerate(split_into_chunks(content)):
            chunks.append(
                {
                    "id": chunk_id(article_idx, chunk_idx),
                    "text": text,
                    "title": title,
                    "url": url,
                }
            )

print(f"{article_idx + 1} articles → {len(chunks)} chunks")
print("first chunk id:", chunks[0]["id"][:16], "…")

14 articles → 90 chunks
first chunk id: 8479b5bf6221a621 …

## 5. Index the Chunks in ChromaDB

Now the chunks go into a persistent ChromaDB collection: embed each batch with `embed()`, then `upsert` vectors, texts, and metadata together. Two details make this cell safe to re-run:

- `get_or_create_collection` opens the collection if it already exists (where `create_collection` would crash on a second run).
- `upsert` overwrites entries whose IDs already exist instead of duplicating them — which works *because* our IDs are deterministic.

`metadata={"hnsw:space": "cosine"}` tells Chroma to rank by cosine distance, the measure we used for retrieval from the start.

In [5]:
import chromadb
from tqdm import tqdm

chroma_client = chromadb.PersistentClient(path="./mini-llama-articles")
collection = chroma_client.get_or_create_collection(
    "mini-llama-articles", metadata={"hnsw:space": "cosine"}
)

BATCH_SIZE = 50
for start in tqdm(range(0, len(chunks), BATCH_SIZE)):
    batch = chunks[start : start + BATCH_SIZE]
    collection.upsert(
        ids=[c["id"] for c in batch],
        embeddings=embed([c["text"] for c in batch], task="document"),
        documents=[c["text"] for c in batch],
        metadatas=[{"title": c["title"], "url": c["url"]} for c in batch],
    )

print(f"Collection holds {collection.count()} chunks")

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.32it/s]

100%|██████████| 2/2 [00:01<00:00,  1.51it/s]

100%|██████████| 2/2 [00:01<00:00,  1.48it/s]

Collection holds 90 chunks

## 6. A Quick End-to-End Check

Before measuring anything, confirm the pipeline works at all: `retrieve()` embeds a question and asks Chroma for the top-k chunks, and `rag_answer()` feeds them to `generate()` through the course augmentation template. These two functions are the *system under test* — everything we measure below, we measure about them.

In [6]:
def retrieve(question, k):
    """Return the top-k chunk IDs and texts for a question."""
    question_embedding = embed(question, task="query")[0]
    results = collection.query(query_embeddings=[question_embedding], n_results=k)
    return results["ids"][0], results["documents"][0]


SYSTEM_INSTRUCTION = (
    "You are an assistant that answers questions using only the provided context. "
    "If the context does not contain the answer, say so."
)

PROMPT_TEMPLATE = (
    "Use the information between the <START_OF_CONTEXT> and <END_OF_CONTEXT> tags "
    "to answer the question.\n\n"
    "<START_OF_CONTEXT>\n{context}\n<END_OF_CONTEXT>\n\n"
    "Provide an informative and accurate answer to the following question based on "
    "the available context. Be concise.\nQuestion: {question}\nAnswer:"
)


def rag_answer(question, k):
    """Retrieve top-k chunks and answer from them. Returns (answer, retrieved_texts)."""
    ids, texts = retrieve(question, k)
    prompt = PROMPT_TEMPLATE.format(context="\n\n".join(texts), question=question)
    return generate(prompt, system=SYSTEM_INSTRUCTION), texts


QUESTION = "How many parameters LLaMA 2 model has?"

retrieved_ids, retrieved_texts = retrieve(QUESTION, k=5)
for rank, (cid, text) in enumerate(zip(retrieved_ids, retrieved_texts), start=1):
    preview = text[:90].replace("\n", " ").strip()
    print(f"Rank {rank} | chunk {cid[:12]}… | {preview}…")

answer, _ = rag_answer(QUESTION, k=5)
print("\nAnswer:", answer)

Rank 1 | chunk 845ac18144a7… | I. Llama 2: Revolutionizing Commercial Use Unlike its predecessor Llama 1, which was limit…
Rank 2 | chunk 40c7970312d6… | vely address a diverse range of questions. This limitation could hinder the model's practi…
Rank 3 | chunk 0346e017ee19… | by Meta that ventures into both the AI and academic spaces. The model aims to help researc…
Rank 4 | chunk 1135c4d9fccd… | un and use the finished model which scale with parameter size). Chinchilla has 70B paramet…
Rank 5 | chunk 423bed853873… | ce and makes Llama 2 a more reliable language model for interactive applications. In the e…

Answer: Based on the provided context, the Llama 2 model is available in four different parameter sizes: 7 billion, 13 billion, 34 billion, and 70 billion.

**What just happened?** The retriever surfaced chunks that talk about Llama 2's sizes, and the answer names the four variants — the pipeline works. But "it works on the one question I tried" is not a measurement. To compare chunking strategies, embedding models, or top-k values, we need *many* questions with known right answers, and metrics computed over all of them. That's what the rest of this notebook builds.

## 7. Build a Synthetic Evaluation Dataset

To evaluate the retriever we need pairs of *(question, the chunk that answers it)*. Writing those by hand is the gold standard — a curated, human-made dataset always beats a generated one — but it is slow. The quick, surprisingly effective alternative: for each chunk, have an LLM write a quiz question that the chunk answers. The chunk's ID becomes the ground-truth label for its question.

Before we generate 25 of them, look at what a single raw completion for this task looks like.

In [7]:
QUESTION_GEN_PROMPT = """\
You are a teacher writing a quiz from course material.
Based only on the context below, write one quiz question that this context can answer.

<context>
{context}
</context>
"""

raw_completion = generate(QUESTION_GEN_PROMPT.format(context=chunks[0]["text"]))
print(raw_completion)

**Question:**
According to the text, what are the three available models that Code Llama is built in?

**(Answer key / Expected response:** Code Llama, Code Llama - Python, and Code Llama - Instruct).

**Look closely at that output — it is free-form text, and the model formatted it however it liked.** In our captured run it added a bolded `**Question:**` header and an answer key we never asked for. Another day (or another model) it might instead add a preamble like "Here is a quiz question:", numbering, quotes, or nothing at all. None of that is a bug — the model was asked for text and produced text.

The bug appears when a *pipeline* consumes this output. Any code that extracts "the question" by splitting lines or stripping prefixes encodes assumptions about formatting the model never promised. Take the completion above: code that keeps the *first line* would save the header `**Question:**` as the question and throw the real question away. And when that happens, nothing errors — you silently store junk strings as your "questions", and every score computed downstream quietly collapses. This is one of the most common ways real eval pipelines fail.

The fix is to **stop parsing**. Every major provider can constrain the model's output to a schema — the same structured-output capability behind tool calling. We define the shape we want as a Pydantic model, and the API guarantees the reply parses into it.

In [8]:
from pydantic import BaseModel


class QuizQuestion(BaseModel):
    question: str


def extract(prompt, schema, system=None, model=None):
    """Like generate(), but the reply is a validated instance of `schema`."""
    if PROVIDER == "gemini":
        response = gemini_client.models.generate_content(
            model=model or MODELS["gemini"],
            contents=prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=system,
                response_mime_type="application/json",
                response_schema=schema,
            ),
        )
        if not isinstance(response.parsed, schema):
            raise ValueError("Model returned no parseable output")
        return response.parsed

    if PROVIDER == "openai":
        response = openai_client.responses.parse(
            model=model or MODELS["openai"],
            instructions=system,
            input=prompt,
            text_format=schema,
            reasoning={"effort": "none"},
        )
        return response.output_parsed

    if PROVIDER == "anthropic":
        response = anthropic_client.messages.parse(
            model=model or MODELS["anthropic"],
            max_tokens=4096,
            **({"system": system} if system else {}),
            messages=[{"role": "user", "content": prompt}],
            output_format=schema,
        )
        return response.parsed_output

    raise ValueError(f"Unknown PROVIDER: {PROVIDER!r}")


sample = extract(QUESTION_GEN_PROMPT.format(context=chunks[0]["text"]), QuizQuestion)
print(type(sample).__name__, "→", sample.question)

QuizQuestion → What parameter spectrum does the Llama 2 model suite span across?

**What just happened?** Same prompt, same model — but this time the API constrained the output to match `QuizQuestion`, and the SDK parsed and validated it into a Python object. There is nothing to split, strip, or regex, so there is nothing to get wrong. `.question` contains the question, whatever mood the model is in.

Each provider spells this differently — Gemini takes a `response_schema`, OpenAI has `responses.parse()`, Anthropic has `messages.parse()` — but the contract is identical: the schema is part of the request, and malformed output becomes the provider's problem instead of yours. **Whenever an LLM's output feeds code instead of a human, make it structured.**

Now generate one question per chunk. We use the first 25 chunks to keep the run fast and cheap (a real project would use the whole corpus), and a small thread pool since the calls are independent.

In [9]:
import uuid
from concurrent.futures import ThreadPoolExecutor

NUM_EVAL_CHUNKS = 25  # keep the demo fast and cheap; scale this up in a real project
eval_chunks = chunks[:NUM_EVAL_CHUNKS]


def question_for_chunk(chunk):
    result = extract(
        QUESTION_GEN_PROMPT.format(context=chunk["text"]), QuizQuestion
    )
    return chunk["id"], result.question


queries, relevant_docs = {}, {}
with ThreadPoolExecutor(max_workers=8) as pool:
    for cid, question in tqdm(pool.map(question_for_chunk, eval_chunks), total=len(eval_chunks)):
        question_id = str(uuid.uuid4())
        queries[question_id] = question
        relevant_docs[question_id] = [cid]

rag_eval_dataset = {
    "queries": queries,  # question_id → question text
    "corpus": {c["id"]: c["text"] for c in eval_chunks},  # chunk_id → chunk text
    "relevant_docs": relevant_docs,  # question_id → [chunk_id]
}
print(f"{len(queries)} questions over {len(eval_chunks)} chunks")

  0%|          | 0/25 [00:00<?, ?it/s]

  4%|▍         | 1/25 [00:00<00:13,  1.79it/s]

 16%|█▌        | 4/25 [00:00<00:02,  7.46it/s]

 36%|███▌      | 9/25 [00:01<00:01,  9.59it/s]

 60%|██████    | 15/25 [00:01<00:00, 13.90it/s]

 68%|██████▊   | 17/25 [00:01<00:00, 10.98it/s]

 96%|█████████▌| 24/25 [00:01<00:00, 17.82it/s]

100%|██████████| 25/25 [00:02<00:00, 11.48it/s]

25 questions over 25 chunks

Generating a dataset costs time and API calls, so save it and reload it in later sessions instead of regenerating. The JSON shape — `queries`, `corpus`, `relevant_docs` — is the standard one for retrieval eval datasets, and `load_dataset()` will happily read any previously saved file with this structure.

In [10]:
import json


def save_dataset(dataset, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(dataset, f, indent=2)


def load_dataset(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


save_dataset(rag_eval_dataset, "rag_eval_dataset.json")
rag_eval_dataset = load_dataset("rag_eval_dataset.json")
print("saved and reloaded:", len(rag_eval_dataset["queries"]), "questions")

saved and reloaded: 25 questions

## 8. Sanity-Check the Questions Before Scoring Anything

**Always eyeball synthetic data before you compute a single score on it.** It takes thirty seconds, and it is the only reliable way to catch a generation problem — off-topic questions, empty strings, questions that lean on context the retriever won't see — *before* it silently poisons every number downstream.

In [11]:
import random

random.seed(42)
for question in random.sample(list(rag_eval_dataset["queries"].values()), 5):
    print("•", question)

• What are the two training methods mentioned that were tried for smaller models during unsupervised learning?
• What tools are leading the LLM revolution according to the context?
• What parameter spectrum does the Meta's Llama 2 model suite span?
• Why is it difficult to fine-tune prompts to give the most effective output?
• Which LangChain utility class serves as a utility for creating a vector store index to store vector representations of documents?

Each printed line should be a specific, self-contained question that our corpus can answer. If you ever see anything else here — headers, preambles, fragments — stop and fix the generation step first. Scores computed on a corrupted dataset measure your bug, not your retriever.

Milder flaws are normal and worth noticing too: a question phrased like "according to the context" leans on a context the retriever never sees. A handful of these is tolerable in a quick synthetic dataset; if they dominate, tighten the generation prompt (for example, add "the question must not refer to the text, the context, or the author").

## 9. Evaluate the Retriever: Hit Rate and MRR

Two metrics, both about where the gold chunk lands in the ranked list the retriever returns:

- **Hit rate** — for what fraction of questions does the gold chunk appear in the top-k at all?
- **MRR (Mean Reciprocal Rank)** — how *high* does it appear? Each question scores 1/rank of its gold chunk (1st place = 1.0, 2nd = 0.5, absent = 0), averaged over all questions.

Both are a few lines of plain Python — the same functions production evaluation harnesses use.

In [12]:
def hit_rate(relevant_id, retrieved_ids):
    """1.0 if the gold chunk appears anywhere in the retrieved list."""
    return 1.0 if relevant_id in retrieved_ids else 0.0


def reciprocal_rank(relevant_id, retrieved_ids):
    """1/rank of the gold chunk in the retrieved list, 0.0 if absent."""
    for rank, chunk_id in enumerate(retrieved_ids, start=1):
        if chunk_id == relevant_id:
            return 1.0 / rank
    return 0.0

In [13]:
import pandas as pd

K_VALUES = [2, 4, 6, 8, 10]


# Retrieve once per question at the largest k — the smaller k results are just
# prefixes of the same ranked list, so one retrieval covers the whole sweep.
def top_ids_for_question(item):
    question_id, question = item
    ids, _ = retrieve(question, k=max(K_VALUES))
    return question_id, ids


with ThreadPoolExecutor(max_workers=8) as pool:
    retrieved = dict(
        tqdm(
            pool.map(top_ids_for_question, rag_eval_dataset["queries"].items()),
            total=len(rag_eval_dataset["queries"]),
        )
    )

rows = []
for k in K_VALUES:
    hits, ranks = [], []
    for question_id, ids in retrieved.items():
        gold_id = rag_eval_dataset["relevant_docs"][question_id][0]
        hits.append(hit_rate(gold_id, ids[:k]))
        ranks.append(reciprocal_rank(gold_id, ids[:k]))
    rows.append(
        {
            "Retriever": f"top_{k}",
            "Hit Rate": sum(hits) / len(hits),
            "MRR": sum(ranks) / len(ranks),
        }
    )

pd.DataFrame(rows)

  0%|          | 0/25 [00:00<?, ?it/s]

  4%|▍         | 1/25 [00:00<00:03,  6.21it/s]

 36%|███▌      | 9/25 [00:00<00:00, 30.56it/s]

 68%|██████▊   | 17/25 [00:00<00:00, 37.99it/s]

100%|██████████| 25/25 [00:00<00:00, 41.16it/s]

100%|██████████| 25/25 [00:00<00:00, 36.77it/s]

  Retriever  Hit Rate       MRR
0     top_2      0.72  0.640000
1     top_4      0.80  0.666667
2     top_6      0.80  0.666667
3     top_8      0.88  0.677381
4    top_10      0.88  0.677381

**What just happened?** Read the table top to bottom. Hit rate climbs as k grows — returning more chunks gives the gold chunk more chances to be included. MRR barely moves, because it rewards *rank*: chunks added at positions 7-10 contribute at most 1/7th of a point each, so extra tail results can't lift it much. Together the two numbers tell you more than either alone: a high hit rate with low MRR means the right chunk is *findable* but buried.

Also resist the "bigger k is better" conclusion. More retrieved chunks means more noise in the prompt and more tokens billed, and the answer model has to sift through it — the next section measures what that does to answer quality.

## 10. Evaluate the Answers: Faithfulness and Relevancy

The retriever finding the right chunk doesn't guarantee the *answer* is good — so next we grade what the pipeline generates. Grading free-form text is exactly the kind of subjective call LLMs are good at, and after Section 7 you know the safe way to collect a model's grade: a typed verdict, not free text we'd have to parse. Two judgments per answer:

- **Faithfulness** — does the answer only state things the retrieved context supports? (This is the hallucination check.)
- **Relevancy** — do the answer and the retrieved context actually address the question?

The judge is `JUDGE_MODEL` — the stronger model role we set up at the start. We run the first 20 questions per k value to keep the demo affordable; in a real evaluation, run them all.

In [14]:
class JudgeVerdict(BaseModel):
    passing: bool
    reasoning: str


FAITHFULNESS_PROMPT = """\
You are grading a RAG system's answer for faithfulness.
Faithful means every claim in the answer is supported by the provided context.
If the answer adds facts that the context does not contain, it fails.

<question>
{question}
</question>

<context>
{context}
</context>

<answer>
{answer}
</answer>

Is the answer faithful to the context? Set passing accordingly and explain briefly.
"""

RELEVANCY_PROMPT = """\
You are grading a RAG system's answer for relevancy.
Relevant means the answer addresses the question that was asked, using retrieved
context that matches the topic of the question.

<question>
{question}
</question>

<context>
{context}
</context>

<answer>
{answer}
</answer>

Are the answer and the retrieved context relevant to the question? Set passing accordingly and explain briefly.
"""


def judge(prompt_template, question, context, answer):
    verdict = extract(
        prompt_template.format(question=question, context=context, answer=answer),
        JudgeVerdict,
        model=JUDGE_MODEL,
    )
    return verdict.passing

In [15]:
EVAL_QUESTIONS = list(rag_eval_dataset["queries"].values())[:20]


def evaluate_question(args):
    question, k = args
    answer, retrieved_texts = rag_answer(question, k)
    context = "\n\n".join(retrieved_texts)
    return (
        judge(FAITHFULNESS_PROMPT, question, context, answer),
        judge(RELEVANCY_PROMPT, question, context, answer),
    )


rows = []
for k in K_VALUES:
    with ThreadPoolExecutor(max_workers=8) as pool:
        verdicts = list(
            tqdm(
                pool.map(evaluate_question, [(q, k) for q in EVAL_QUESTIONS]),
                total=len(EVAL_QUESTIONS),
                desc=f"top_{k}",
            )
        )
    rows.append(
        {
            "Query Engine": f"top_{k}",
            "Faithfulness": sum(f for f, _ in verdicts) / len(verdicts),
            "Relevancy": sum(r for _, r in verdicts) / len(verdicts),
        }
    )

pd.DataFrame(rows)

top_2:   0%|          | 0/20 [00:00<?, ?it/s]

top_2:   5%|▌         | 1/20 [00:04<01:20,  4.23s/it]

top_2:  10%|█         | 2/20 [00:04<00:33,  1.85s/it]

top_2:  15%|█▌        | 3/20 [00:04<00:19,  1.15s/it]

top_2:  45%|████▌     | 9/20 [00:07<00:06,  1.71it/s]

top_2:  50%|█████     | 10/20 [00:08<00:06,  1.63it/s]

top_2:  55%|█████▌    | 11/20 [00:08<00:05,  1.71it/s]

top_2:  70%|███████   | 14/20 [00:09<00:02,  2.11it/s]

top_2:  85%|████████▌ | 17/20 [00:12<00:01,  1.51it/s]

top_2:  90%|█████████ | 18/20 [00:14<00:01,  1.20it/s]

top_2: 100%|██████████| 20/20 [00:14<00:00,  1.41it/s]

top_4:   0%|          | 0/20 [00:00<?, ?it/s]

top_4:   5%|▌         | 1/20 [00:04<01:24,  4.45s/it]

top_4:  10%|█         | 2/20 [00:05<00:42,  2.36s/it]

top_4:  15%|█▌        | 3/20 [00:05<00:23,  1.35s/it]

top_4:  45%|████▌     | 9/20 [00:07<00:05,  1.99it/s]

top_4:  50%|█████     | 10/20 [00:08<00:05,  1.71it/s]

top_4:  60%|██████    | 12/20 [00:08<00:03,  2.22it/s]

top_4:  70%|███████   | 14/20 [00:09<00:02,  2.10it/s]

top_4:  85%|████████▌ | 17/20 [00:11<00:01,  1.87it/s]

top_4:  90%|█████████ | 18/20 [00:13<00:01,  1.39it/s]

top_4: 100%|██████████| 20/20 [00:13<00:00,  1.52it/s]

top_6:   0%|          | 0/20 [00:00<?, ?it/s]

top_6:   5%|▌         | 1/20 [00:04<01:26,  4.53s/it]

top_6:  10%|█         | 2/20 [00:05<00:41,  2.30s/it]

top_6:  45%|████▌     | 9/20 [00:07<00:06,  1.82it/s]

top_6:  50%|█████     | 10/20 [00:07<00:05,  1.95it/s]

top_6:  55%|█████▌    | 11/20 [00:07<00:04,  2.05it/s]

top_6:  65%|██████▌   | 13/20 [00:08<00:02,  2.66it/s]

top_6:  70%|███████   | 14/20 [00:09<00:03,  1.68it/s]

top_6:  85%|████████▌ | 17/20 [00:10<00:01,  1.84it/s]

top_6:  90%|█████████ | 18/20 [00:16<00:02,  1.38s/it]

top_6: 100%|██████████| 20/20 [00:16<00:00,  1.23it/s]

top_8:   0%|          | 0/20 [00:00<?, ?it/s]

top_8:   5%|▌         | 1/20 [00:04<01:22,  4.35s/it]

top_8:  10%|█         | 2/20 [00:05<00:45,  2.53s/it]

top_8:  45%|████▌     | 9/20 [00:07<00:06,  1.63it/s]

top_8:  60%|██████    | 12/20 [00:08<00:03,  2.19it/s]

top_8:  70%|███████   | 14/20 [00:09<00:03,  1.88it/s]

top_8:  85%|████████▌ | 17/20 [00:11<00:01,  1.81it/s]

top_8:  90%|█████████ | 18/20 [00:13<00:01,  1.38it/s]

top_8: 100%|██████████| 20/20 [00:13<00:00,  1.52it/s]

top_10:   0%|          | 0/20 [00:00<?, ?it/s]

top_10:   5%|▌         | 1/20 [00:04<01:25,  4.49s/it]

top_10:  10%|█         | 2/20 [00:04<00:34,  1.91s/it]

top_10:  30%|███       | 6/20 [00:05<00:08,  1.74it/s]

top_10:  45%|████▌     | 9/20 [00:07<00:06,  1.64it/s]

top_10:  55%|█████▌    | 11/20 [00:07<00:04,  2.06it/s]

top_10:  60%|██████    | 12/20 [00:07<00:03,  2.38it/s]

top_10:  65%|██████▌   | 13/20 [00:08<00:02,  2.41it/s]

top_10:  70%|███████   | 14/20 [00:09<00:03,  1.57it/s]

top_10:  85%|████████▌ | 17/20 [00:11<00:01,  1.53it/s]

top_10:  90%|█████████ | 18/20 [00:13<00:01,  1.21it/s]

top_10: 100%|██████████| 20/20 [00:13<00:00,  1.52it/s]

  Query Engine  Faithfulness  Relevancy
0        top_2          0.95        1.0
1        top_4          0.95        1.0
2        top_6          0.95        1.0
3        top_8          1.00        1.0
4       top_10          0.95        1.0

**What just happened?** For every k, the pipeline answered 20 questions and the judge graded each answer twice — faithfulness and relevancy — through the same `extract()` helper, just with a verdict schema and the stronger judge model. Expect scores near the top of the 0-1 range: on a small, clean corpus, with questions generated *from that corpus*, the pipeline is answering questions whose evidence it definitely holds, so passing both checks is the norm (our captured run scored 0.95-1.0 across the sweep). These metrics earn their keep when something changes — swap the embedding model, shrink k, ingest noisier documents — and a drop in these scores is how you find out.

But notice what these metrics *cannot* see: an answer can be faithful to retrieved context and relevant to the question, and still be **factually wrong** — wrong because the corpus is wrong, or because the model garbled a detail the judge has no reference to check against. For that we need one more metric.

## 11. Correctness: Judging Against a Reference Answer

**Correctness** compares a generated answer to a ground-truth *reference* answer and scores it 0-5. It is the strictest metric in this lesson and the most expensive to set up, because someone has to write the references. The verdict gains a `score` and a written `feedback` explaining what was wrong — often the most useful output of the whole evaluation.

To see it catch a real error, we hand it a fabricated answer: the response below correctly covers special relativity, then claims general relativity is about *magnetism* warping spacetime.

In [16]:
class CorrectnessVerdict(BaseModel):
    score: float
    feedback: str


CORRECTNESS_PROMPT = """\
You are grading a generated answer against a reference answer.

Score the generated answer from 0 to 5:
- 5: fully correct and complete, equivalent to the reference
- 4: correct with minor omissions
- 3: mostly correct with small errors
- 2: partially correct with significant errors
- 1: mostly incorrect
- 0: entirely incorrect or off-topic

<question>
{question}
</question>

<reference_answer>
{reference}
</reference_answer>

<generated_answer>
{response}
</generated_answer>

Set score, and explain in feedback which parts are wrong or missing.
"""

query = "Can you explain the theory of relativity proposed by Albert Einstein in detail?"

reference = """
Certainly! Albert Einstein's theory of relativity consists of two main components: special relativity and general relativity. Special relativity, published in 1905, introduced the concept that the laws of physics are the same for all non-accelerating observers and that the speed of light in a vacuum is a constant, regardless of the motion of the source or observer. It also gave rise to the famous equation E=mc², which relates energy (E) and mass (m).

General relativity, published in 1915, extended these ideas to include the effects of gravity. According to general relativity, gravity is not a force between masses, as described by Newton's theory of gravity, but rather the result of the warping of space and time by mass and energy. Massive objects, such as planets and stars, cause a curvature in spacetime, and smaller objects follow curved paths in response to this curvature. This concept is often illustrated using the analogy of a heavy ball placed on a rubber sheet, causing it to create a depression that other objects (representing smaller masses) naturally move towards.

In essence, general relativity provided a new understanding of gravity, explaining phenomena like the bending of light by gravity (gravitational lensing) and the precession of the orbit of Mercury. It has been confirmed through numerous experiments and observations and has become a fundamental theory in modern physics.
"""

response = """
Certainly! Albert Einstein's theory of relativity consists of two main components: special relativity and general relativity. Special relativity, published in 1905, introduced the concept that the laws of physics are the same for all non-accelerating observers and that the speed of light in a vacuum is a constant, regardless of the motion of the source or observer. It also gave rise to the famous equation E=mc², which relates energy (E) and mass (m).

However, general relativity, published in 1915, extended these ideas to include the effects of magnetism. According to general relativity, gravity is not a force between masses but rather the result of the warping of space and time by magnetic fields generated by massive objects. Massive objects, such as planets and stars, create magnetic fields that cause a curvature in spacetime, and smaller objects follow curved paths in response to this magnetic curvature. This concept is often illustrated using the analogy of a heavy ball placed on a rubber sheet with magnets underneath, causing it to create a depression that other objects (representing smaller masses) naturally move towards due to magnetic attraction.
"""

In [17]:
verdict = extract(
    CORRECTNESS_PROMPT.format(question=query, reference=reference, response=response),
    CorrectnessVerdict,
    model=JUDGE_MODEL,
)
print("score:", verdict.score)
print(verdict.feedback)

score: 2.0
The generated answer correctly explains special relativity, but contains significant errors regarding general relativity. It incorrectly states that general relativity deals with magnetism, magnetic fields, and magnetic attraction causing spacetime curvature, rather than mass and energy warping spacetime to produce gravity. It also omits the real-world applications and observational confirmations mentioned in the reference answer.

**What just happened?** The judge scored the fabricated answer low and — read the feedback — named the exact fabrication: general relativity is about mass-energy warping spacetime, not magnetism. Notice that faithfulness and relevancy would likely have *passed* this answer if the corpus itself contained the error: it is fluent, on-topic, and internally consistent. Only a comparison against a trusted reference catches it.

That is the trade-off of correctness: it is the strongest signal, and the only one that needs a curated question-and-answer dataset. Building one is slow, but you build it once and it evaluates every version of your pipeline for the lifetime of the project.

## 🔑 Key Takeaways

- Evaluate a RAG pipeline on **two axes**: the retriever (does the right chunk come back, and how high?) and the answers (faithful, relevant, correct?).
- A synthetic eval dataset is *(question, gold-chunk ID)* pairs generated per chunk — which is why **deterministic chunk IDs** matter: the saved dataset must still point at the same chunks next run.
- **Generate synthetic data with structured output.** Free-form completions require parsing, parsing encodes assumptions, and broken assumptions don't error — they silently corrupt every score downstream.
- **Eyeball your synthetic data before scoring.** Five random samples take thirty seconds and catch what no metric will tell you.
- **Hit rate and MRR are ~ten lines of Python.** Sweep top-k and read them together: hit rate measures findability, MRR measures ranking.
- **LLM judges return typed verdicts** (`passing`/`reasoning`, `score`/`feedback`) through the same `extract()` helper — and the judge should be at least as strong as the model it grades.
- Faithfulness and relevancy don't need ground truth; **correctness does** — it is the strongest check and the most expensive to set up.

This lesson evaluated the retriever and single answers in isolation. The Section 13 lessons evaluate the whole agent — cost, latency, and answer quality over full multi-turn conversations.