<a href="https://colab.research.google.com/github/towardsai/ai-tutor-rag-system/blob/main/notebooks/08-Finetune_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fine-Tuning an Embedding Model

Retrieval is only ever as good as the vectors it searches. When your corpus speaks a dialect the embedder never really read — internal product names, house jargon, a research niche — a general-purpose model parks the right chunk at rank 9 instead of rank 1, and nothing downstream repairs that: the generator can only read what retrieval handed it.

This lesson does something about it. We take `BAAI/bge-small-en-v1.5`, mine training pairs out of the AI-Tutor corpus itself, **fine-tune the model** with `sentence-transformers` and `MultipleNegativesRankingLoss`, and measure before against after on a held-out split using the course's own `hit_rate()` and `mrr()`.

📎 *Every pipeline function below was built by hand in Sections 3–4 and in "Evaluating Your RAG Pipeline", and is re-pasted here in plain Python. The genuinely new thing in this notebook is the training loop.*

⏭️ *An earlier version of this lesson trained a small adapter on top of a frozen base model. We now fine-tune the model itself — the standard `sentence-transformers` recipe, and the one behind every model card and training script you will meet in the wild.*

## 🧭 What You'll Learn

- When fine-tuning an embedder is worth it — and the cheaper alternative you should price **first**
- Turning a raw corpus into **(question, positive-chunk) training pairs** with one typed LLM call per chunk
- Why **`MultipleNegativesRankingLoss`** is the natural loss for retrieval, and why its batch size is a *quality* knob rather than just a memory knob
- Training with `SentenceTransformerTrainer` — the standard recipe, in about fifteen lines
- Measuring before and after on the **same held-out split** with the same `hit_rate()` and `mrr()`, so the improvement is a number instead of a hope

## 1. Setup: Environment, Keys, and Providers

One setup cell installs the pinned SDK profile, loads your keys, and picks the models. This lesson's extra is `sentence-transformers`, which brings the trainer with it. The **model fields are editable dropdowns** — choose a listed default or type any newer model ID. (Locally, edit the string.)

A GPU runtime turns training into a minute or two; CPU still finishes at the default sizes, just slower. In Colab: *Runtime → Change runtime type → T4 GPU*.

In [1]:
# ============================================================
# ⚙️ Setup — environment, dependencies, API keys, provider
# ============================================================
import os
import sys

IN_COLAB = "google.colab" in sys.modules

# Pick your model providers (dropdowns in Colab; edit the values locally)
PROVIDER = "gemini"  # @param ["gemini", "openai", "anthropic"]
EMBED_PROVIDER = "gemini"  # @param ["gemini", "openai"]  (Anthropic has no embedding API)

# Pick a model for the selected provider — or TYPE any newer model ID into the
# box (the dropdown is editable thanks to allow-input):
CHAT_MODEL = "gemini-3.8-flash"  # @param ["gemini-3.8-flash", "gemini-3.5-flash-lite", "gpt-5.6-luna", "claude-sonnet-5"] {allow-input: true}
EMBED_MODEL = "gemini-embedding-001"  # @param ["gemini-embedding-001", "text-embedding-3-small"] {allow-input: true}

# The open-weight model we FINE-TUNE in this lesson. Small models are the ones
# that gain most from training, and this one runs anywhere.
BASE_MODEL = "BAAI/bge-small-en-v1.5"  # @param ["BAAI/bge-small-en-v1.5", "BAAI/bge-base-en-v1.5", "sentence-transformers/all-MiniLM-L6-v2"] {allow-input: true}

_KEY_FOR = {"gemini": "GOOGLE_API_KEY", "openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}
REQUIRED_KEYS = sorted({_KEY_FOR[PROVIDER], _KEY_FOR[EMBED_PROVIDER]})

if IN_COLAB:
    import importlib
    import site
    import subprocess

    # Shared install profile, pinned course-wide (July 2026). This lesson's extra
    # is sentence-transformers; the [train] extra adds the datasets + accelerate
    # packages that SentenceTransformerTrainer needs.
    subprocess.run(
        [
            sys.executable, "-m", "pip", "install", "-q", "-U",
            "google-genai==2.3.0",
            "openai==2.46.0",
            "anthropic==0.117.0",
            "chromadb==1.5.9",
            "tiktoken==0.13.0",
            "sentence-transformers[train]==5.5.1",
        ],
        check=True,
    )
    importlib.reload(site)  # make newly installed packages importable without a runtime restart

    # In Colab: Secrets tab (🔑 icon) → Add new secret → e.g. GOOGLE_API_KEY
    from google.colab import userdata

    for key in REQUIRED_KEYS:
        os.environ[key] = userdata.get(key)

if not IN_COLAB:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")

    # Locally: dependencies are installed once from the repo's requirements.
    # Keys live in a .env file at the repo root.
    from dotenv import load_dotenv

    load_dotenv()
    missing = [k for k in REQUIRED_KEYS if not os.getenv(k)]
    assert not missing, f"Missing from .env: {missing}"

import torch

if torch.cuda.is_available():
    DEVICE = "cuda"
elif torch.backends.mps.is_available():
    DEVICE = "mps"
else:
    DEVICE = "cpu"

print(f"✅ Setup complete — {'Colab' if IN_COLAB else 'local'} | chat: {PROVIDER} | fine-tuning {BASE_MODEL} on {DEVICE}")

✅ Setup complete — local | chat: gemini | fine-tuning BAAI/bge-small-en-v1.5 on mps

## 2. Why Fine-Tune an Embedder at All?

An embedding model is a compression of everything it was trained on. General-purpose embedders learn from web-scale text, which makes them excellent at general English and merely *adequate* at your domain: the model knows "transformer" is a neural architecture, but not that in your handbook `Transformer` is the name of the billing service. Fine-tuning moves the vector space so that the questions **your users actually ask** land next to the chunks that **actually answer them**.

Three things typically improve:

- **Vocabulary.** Rare, domain-specific tokens stop being noise and start carrying signal.
- **Query/document alignment.** Users ask short questions; documents are long prose. Training on real (question, chunk) pairs teaches the model to bridge that gap directly.
- **Ranking, not just recall.** The gold chunk moves *up* the list — which is what MRR measures, and what the generator actually reads with the most attention.

### The honest alternative: price the boring option first

Fine-tuning buys you a training pipeline to maintain, a held-out split to keep clean, a model artifact to version, and a **full re-embedding of your corpus every time you retrain**. Before paying that, price the boring alternative: **swap in a stronger off-the-shelf embedder**. A top-tier hosted model frequently beats a fine-tuned small one outright, and its "training run" is a one-line edit in the setup cell.

And this lesson's original hedge still stands, unchanged: **if your domain closely matches the pre-trained model's data, or your fine-tuning dataset is limited, using the model as-is may be more effective.** Carefully assess your needs, resources, and expected improvement before fine-tuning. Section 9 says what we did in production, and why.

## 3. The Pipeline, Redefined in Plain Python

Everything this notebook borrows, with a 📎 note naming the lesson that built it. Nothing here is new machinery — it is the same code you wrote in Sections 3–4, pasted once so the rest of the notebook can be about training, not plumbing.

In [2]:
# 📎 generate() and embed() — the two course helpers, exactly as built in
#    "How To Use LLMs via API" and "Basic RAG". generate() writes this lesson's
#    training questions; embed() is the hosted embedder that Section 9's
#    "just upgrade the base model" argument is really about.
from anthropic import Anthropic
from google import genai
from google.genai import types as genai_types
from openai import OpenAI

# Course-standard default models per provider (August 2026)
MODELS = {
    "gemini": "gemini-3.8-flash",
    "openai": "gpt-5.6-luna",
    "anthropic": "claude-sonnet-5",
}

# The setup-cell form selection (or any typed model ID) overrides the default:
MODELS[PROVIDER] = CHAT_MODEL
EMBED_MODELS = {
    "gemini": "gemini-embedding-001",
    "openai": "text-embedding-3-small",
}
EMBED_MODELS[EMBED_PROVIDER] = EMBED_MODEL  # setup-cell selection (or typed ID) wins
EMBED_DIM = 1536  # same output size for both providers, so the rest of the code never cares

# Create only the clients we actually need
if "gemini" in (PROVIDER, EMBED_PROVIDER):
    gemini_client = genai.Client()
if "openai" in (PROVIDER, EMBED_PROVIDER):
    openai_client = OpenAI()
if PROVIDER == "anthropic":
    anthropic_client = Anthropic()


def generate(prompt, system=None, model=None):
    """Send one prompt to the selected PROVIDER and return the reply text."""
    if PROVIDER == "gemini":
        interaction = gemini_client.interactions.create(
            model=model or MODELS["gemini"],
            input=prompt,
            # pass system_instruction only when set (None would be sent as JSON null)
            **({"system_instruction": system} if system else {}),
        )
        return interaction.output_text

    if PROVIDER == "openai":
        response = openai_client.responses.create(
            model=model or MODELS["openai"],
            instructions=system,
            input=prompt,
            reasoning={"effort": "none"},
        )
        return response.output_text

    if PROVIDER == "anthropic":
        response = anthropic_client.messages.create(
            model=model or MODELS["anthropic"],
            max_tokens=4096,
            **({"system": system} if system else {}),
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    raise ValueError(f"Unknown PROVIDER: {PROVIDER!r}")


def embed(texts, task="document"):
    """Embed a list of texts with the selected EMBED_PROVIDER.

    Returns a list of EMBED_DIM-dimensional vectors (one per input text).
    task: "document" for corpus chunks, "query" for user questions —
    Gemini embeds the two slightly differently to improve retrieval.
    """
    if isinstance(texts, str):
        texts = [texts]
    # Embedding models work best on single-line inputs
    texts = [t.replace("\n", " ") for t in texts]

    if EMBED_PROVIDER == "gemini":
        result = gemini_client.models.embed_content(
            model=EMBED_MODELS["gemini"],
            contents=texts,
            config=genai_types.EmbedContentConfig(
                task_type="RETRIEVAL_DOCUMENT" if task == "document" else "RETRIEVAL_QUERY",
                output_dimensionality=EMBED_DIM,
            ),
        )
        return [e.values for e in result.embeddings]

    if EMBED_PROVIDER == "openai":
        result = openai_client.embeddings.create(
            model=EMBED_MODELS["openai"], input=texts
        )
        return [d.embedding for d in result.data]

    raise ValueError(f"Unknown EMBED_PROVIDER: {EMBED_PROVIDER!r}")

In [3]:
# 📎 The pipeline functions, named after the lesson that built each one.
import chromadb
import tiktoken

# — chunk() and n_tokens(): "From Script to Pipeline"
ENC = tiktoken.get_encoding("cl100k_base")


def n_tokens(text):
    """Number of tokens in a string."""
    return len(ENC.encode(text))


def chunk(text, chunk_size=512, chunk_overlap=128):
    """Split text into token-based chunks; consecutive chunks share chunk_overlap tokens."""
    tokens = ENC.encode(text)
    chunks = []
    step = chunk_size - chunk_overlap
    for start in range(0, len(tokens), step):
        window = tokens[start : start + chunk_size]
        chunks.append(ENC.decode(window))
        if start + chunk_size >= len(tokens):
            break  # the final window reached the end of the text
    return chunks


# — get_collection(), index_chunks() and search(): the ingestion loop from the
#   vector-database lesson, carrying the embed_fn= seam that "Selecting the Right
#   Embedding Model" added. That seam is what lets ONE evaluator score two models.
DB_PATH = "./finetune-embedding-chroma"


def get_collection(name, path=DB_PATH):
    """A persistent Chroma collection with cosine distance."""
    client = chromadb.PersistentClient(path=path)
    return client.get_or_create_collection(
        name=name,
        metadata={"hnsw:space": "cosine"},  # distance = 1 - cosine similarity
    )


def index_chunks(records, collection, embed_fn, batch_size=64):
    """Embed already-chunked records with embed_fn and upsert them under their stable ids."""
    for start in range(0, len(records), batch_size):
        batch = records[start : start + batch_size]
        collection.upsert(
            ids=[r["id"] for r in batch],
            documents=[r["text"] for r in batch],
            embeddings=embed_fn([r["text"] for r in batch], task="document"),
            metadatas=[{"title": r["title"], "url": r["url"], "source": r["source"]} for r in batch],
        )
    return len(records)


def search(query, collection, top_k=5, embed_fn=None):
    """Dense retrieval against one collection, embedding the query with embed_fn."""
    embed_fn = embed_fn or embed
    result = collection.query(
        query_embeddings=[embed_fn(query, task="query")[0]], n_results=top_k
    )
    return [
        {"id": cid, "text": doc, "score": 1 - dist, **meta}
        for cid, doc, dist, meta in zip(
            result["ids"][0], result["documents"][0],
            result["distances"][0], result["metadatas"][0],
        )
    ]


def show_chunks(hits, max_chars=120):
    """Print retrieved chunks with scores — look before you measure."""
    for r in hits:
        preview = r["text"][:max_chars].replace("\n", " ")
        print(f"  {r['score']:.4f} | {r['title'][:40]:40} | {preview}…")

## 4. The Corpus: Load, Split by Document, Then Chunk

We train on the real thing: the `ai_tutor_knowledge` corpus (788 documents of framework and tool documentation (LangChain, LlamaIndex, the OpenAI and Claude Code docs, LangGraph, Deep Agents) plus Agent Engineering course lessons — the production tutor's raw material), the same file behind the retrieval lessons' prebuilt stores.

The one rule that decides whether this whole notebook means anything: **split by document, before chunking.** Chunks overlap by 128 tokens, so splitting after chunking would drop two overlapping halves of the same article on opposite sides of the split — and the "improvement" you measured afterwards would be partly memorisation. Documents in, split, *then* chunk.

In [4]:
# @title ⚙️ Corpus and training knobs { display-mode: "form" }
# (N_ARTICLES=120, N_TRAIN_PAIRS=250, EPOCHS=2) to keep this execution short
# and cheap. The outputs below reflect this smaller sample, not a full run.
N_ARTICLES = 120  # @param {type:"integer"}
TEST_SPLIT = 0.15  # @param {type:"number"}
N_TRAIN_PAIRS = 250  # @param {type:"integer"}
N_TEST_PAIRS = 60  # @param {type:"integer"}
EPOCHS = 3  # @param {type:"integer"}
BATCH_SIZE = 32  # @param {type:"integer"}
MAX_SEQ_LEN = 512  # @param {type:"integer"}
MINI_BATCH_SIZE = 4  # @param {type:"integer"}
TOP_K = 5  # @param {type:"integer"}
# 120 documents ≈ 600-800 chunks. Building the pair sets costs one LLM call per
# sampled chunk (N_TRAIN_PAIRS + N_TEST_PAIRS calls — minutes, cents), and both
# sets are cached to disk so a rerun costs nothing. Training 250 pairs for 2
# epochs is about a minute on a T4 and a few minutes on CPU.
print(f"training on {DEVICE} — batch {BATCH_SIZE}, {MAX_SEQ_LEN} tokens/chunk")

training on mps — batch 32, 512 tokens/chunk

In [5]:
import json
import pathlib
import random

import requests

# 📎 The course download cell, unchanged — dataset hosted in the Towards AI org
#    dataset repo on Hugging Face.
DATA_URL = "https://huggingface.co/datasets/towardsai-tutors/full-stack-ai-engineering-data/resolve/main/ai_tutor_knowledge.jsonl"
DATA_PATH = pathlib.Path("ai_tutor_knowledge.jsonl")

if not DATA_PATH.exists():
    DATA_PATH.write_bytes(requests.get(DATA_URL, timeout=180).content)
    print("Downloaded", DATA_PATH)

with open(DATA_PATH, encoding="utf-8") as f:
    docs_all = [json.loads(line) for line in f]

docs = docs_all[:N_ARTICLES]  # the size knob

# Split DOCUMENTS, not chunks — and with a fixed seed, so "the held-out split"
# means the same thing on every rerun and across the before/after comparison.
random.Random(42).shuffle(docs)
split_at = int(len(docs) * (1 - TEST_SPLIT))
train_docs, test_docs = docs[:split_at], docs[split_at:]


# 📎 The chunking loop out of ingest(): token-based chunks, stable ids built from
#    the dataset's own doc_id plus the chunk's position.
def to_records(documents, chunk_size=512, chunk_overlap=128):
    records = []
    for doc in documents:
        for i, piece in enumerate(chunk(doc["content"], chunk_size, chunk_overlap)):
            records.append({
                "id": f"{doc['doc_id']}-{i}",
                "text": piece,
                "title": doc["name"],
                "url": doc["url"],
                "source": doc["source"],
            })
    return records


train_records = to_records(train_docs)
test_records = to_records(test_docs)

print(f"{len(docs_all)} documents in the corpus — using the first {len(docs)}")
print(f"train: {len(train_docs):>3} documents → {len(train_records):>4} chunks")
print(f"test:  {len(test_docs):>3} documents → {len(test_records):>4} chunks (never seen during training)")

788 documents in the corpus — using the first 120
train: 102 documents → 1719 chunks
test:   18 documents →  443 chunks (never seen during training)

**What just happened?** The production corpus went through the same `chunk()` you wrote in Section 3, and came out as two disjoint pools of records with stable ids. The training pool feeds the trainer; the test pool becomes the index we search in Sections 6 and 8. Because no document contributes chunks to both pools, a gain measured later is a gain on text the model genuinely never saw.

## 5. Synthetic Training Pairs — and a Held-Out Test Set

Fine-tuning a retriever needs *(question, the chunk that answers it)* pairs. Almost nobody has those lying around for their own domain, so we manufacture them the same way the evaluation lesson manufactured its eval set: show each chunk to the LLM, ask for a question that chunk can answer **on its own**, and keep that chunk's id as the label.

📎 *`make_qa_pairs()` is the evaluation lesson's function, with one seam widened: it takes `(records)` instead of a Chroma collection, because the training half of this notebook never indexes anything. The parsing is unchanged and deliberately strict — `json.loads`, never `eval()`.*

The exact same function builds both sets. Only the pool it draws from differs, and that is what makes the test set honest: **training questions come from training documents, test questions from held-out documents.**

💡 *Synthetic pairs are the fast, cheap way to start, and they inherit the corpus's blind spots. A few hundred human-written pairs from real user logs beats a few thousand synthetic ones — collect them as soon as you have traffic.*

In [6]:
from pathlib import Path

# 📎 make_qa_pairs() from "Evaluating Your RAG Pipeline" — same prompt, same strict
#    JSON parse, same (question, gold chunk_id) output. Only the input seam moved.
QA_GEN_PROMPT = """Context information is below.
---------------------
{context}
---------------------
Given ONLY the context above and no prior knowledge, write {n} quiz question(s)
that this context can answer on its own. Questions must be self-contained.

Return ONLY a JSON array of question strings, e.g. ["What is X?"]"""


def _parse_json(raw):
    return json.loads(raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip())


def make_qa_pairs(records, n_chunks=25, questions_per_chunk=1, seed=0):
    """Generate (question, gold chunk_id) pairs from a sample of chunks."""
    sample = random.Random(seed).sample(records, min(n_chunks, len(records)))
    qa_pairs = []
    for rec in sample:
        raw = generate(QA_GEN_PROMPT.format(context=rec["text"], n=questions_per_chunk))
        try:
            questions = _parse_json(raw)
        except json.JSONDecodeError:
            continue  # skip a malformed generation rather than crash the run
        for q in questions[:questions_per_chunk]:
            qa_pairs.append({"question": q, "chunk_id": rec["id"]})
    return qa_pairs


def build_pairs(path, records, n_chunks, seed):
    """Generate once, cache to JSON, reload on every later run (and re-pay nothing)."""
    path = Path(path)
    if path.exists():
        pairs = json.loads(path.read_text())
        print(f"Loaded {len(pairs)} pairs from {path}")
    else:
        pairs = make_qa_pairs(records, n_chunks=n_chunks, seed=seed)
        path.write_text(json.dumps(pairs, indent=2))
        print(f"Generated and saved {len(pairs)} pairs to {path}")
    return pairs


train_pairs = build_pairs("finetune_train_pairs.json", train_records, N_TRAIN_PAIRS, seed=0)
test_pairs = build_pairs("finetune_test_pairs.json", test_records, N_TEST_PAIRS, seed=1)

print("\nOne training pair:")
print("  question:", train_pairs[0]["question"])
print("  positive:", train_pairs[0]["chunk_id"])

/var/folders/9p/l_87mhdx40z2_bhn96_szrwm0000gn/T/ipykernel_7316/4183756661.py:38: UserWarning: Interactions usage is experimental and may change in future versions.
  interaction = gemini_client.interactions.create(

Generated and saved 250 pairs to finetune_train_pairs.json
Generated and saved 60 pairs to finetune_test_pairs.json

One training pair:
  question: What is the minimum version of the Claude in Chrome extension required to connect Claude to the Chrome browser?
  positive: e750cfbf-e324-5503-bb4d-fd8c664dbc04-9

**What just happened?** Two label sets, one generator. `train_pairs` is what the model will learn from; `test_pairs` is what it will be graded on, drawn from documents it will never train on. Both are cached as plain JSON, so every rerun of this notebook grades against *identical* questions — which is the only way a before/after comparison means anything.

## 6. Baseline: the Off-the-Shelf `bge-small`

Never report an improvement without the number it improved on. So before any training happens, we index the held-out chunks with the untouched model and score it with the course's retrieval metrics.

📎 *`hit_rate()` and `mrr()` are the ten-liners from "Evaluating Your RAG Pipeline". The only change is the one the embedding-selection lesson already made: the retriever is passed in, so the **same two functions** can grade two different models on the same questions.*

One trap worth naming: `SentenceTransformerTrainer` mutates the model object **in place**. Share one object between the baseline and the training run and your "before" numbers quietly become your "after" numbers. So the baseline gets its own load.

In [7]:
from sentence_transformers import SentenceTransformer

# 📎 sentence-transformers conventions from "Selecting the Right Embedding Model":
#    load once, encode with normalize_embeddings=True, and keep the
#    (texts, task=...) contract so index_chunks()/search() cannot tell embedders
#    apart. BAAI/bge-small-en-v1.5 is NOT instruction-tuned, so that lesson's
#    _QUERY_PROMPTS map correctly yields no prefix: documents and queries are
#    encoded identically here.
def embedder_for(model, batch_size=64):
    """An embed()-shaped view of a SentenceTransformer: (texts, task=...) -> vectors."""

    def embed_fn(texts, task="document"):
        if isinstance(texts, str):
            texts = [texts]
        vectors = model.encode(texts, normalize_embeddings=True, batch_size=batch_size)
        return [v.tolist() for v in vectors]

    return embed_fn


# Its OWN load: Section 7 trains a separate copy, so this one stays "before".
base_model = SentenceTransformer(BASE_MODEL, device=DEVICE)
base_model.max_seq_length = MAX_SEQ_LEN  # the SAME truncation the tuned model gets
base_embed = embedder_for(base_model)

base_collection = get_collection("finetune_baseline")
index_chunks(test_records, base_collection, embed_fn=base_embed)
print(f"Held-out index ready: {base_collection.count()} chunks\n")

# Always LOOK at retrieval before measuring it.
show_chunks(search(test_pairs[0]["question"], base_collection, top_k=3, embed_fn=base_embed))
print("\nquestion:  ", test_pairs[0]["question"])
print("gold chunk:", test_pairs[0]["chunk_id"])

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Held-out index ready: 574 chunks

  0.7480 | LangGraph runtime                        |  ```python     print(graph.nodes)     ```      You will see something like this:      ```pycon     {'__start__': <langgr…
  0.7238 | Persistence                              |  the next node to be executed * Checkpoint with the outputs of `node_a` `{'foo': 'a', 'bar': ['a']}` and `node_b` as the…
  0.7178 | Persistence                              | node_a") workflow.add_edge("node_a", "node_b") workflow.add_edge("node_b", END)  checkpointer = InMemorySaver() graph = …

question:   According to the provided output for `print(graph.nodes)`, what are the names of the three nodes contained in the graph dictionary?
gold chunk: 62f13576-68b8-5a06-8f5d-3fc88dce48c3-13

In [8]:
# 📎 hit_rate() and mrr() from "Evaluating Your RAG Pipeline" — unchanged except
#    that the retriever arrives as an argument (the search_fn seam), so ONE pair
#    of functions grades every model in this notebook.
def hit_rate(qa_pairs, search_fn, top_k=5):
    """Fraction of questions whose gold chunk appears in the top_k results."""
    hits = 0
    for pair in qa_pairs:
        ids = [r["id"] for r in search_fn(pair["question"], top_k)]
        hits += pair["chunk_id"] in ids
    return hits / len(qa_pairs)


def mrr(qa_pairs, search_fn, top_k=5):
    """Mean Reciprocal Rank: 1/rank of the gold chunk (0 if absent), averaged."""
    total = 0.0
    for pair in qa_pairs:
        ids = [r["id"] for r in search_fn(pair["question"], top_k)]
        if pair["chunk_id"] in ids:
            total += 1 / (ids.index(pair["chunk_id"]) + 1)
    return total / len(qa_pairs)


def retriever_for(collection, embed_fn):
    """A (query, top_k) -> hits view of one index, for the metrics."""
    return lambda query, top_k: search(query, collection, top_k=top_k, embed_fn=embed_fn)


base_retriever = retriever_for(base_collection, base_embed)
baseline_scores = {
    "hit_rate": hit_rate(test_pairs, base_retriever, top_k=TOP_K),
    "mrr": mrr(test_pairs, base_retriever, top_k=TOP_K),
}

print(f"BASELINE — {BASE_MODEL}, off the shelf")
print(f"  {len(test_pairs)} held-out questions, top_k={TOP_K}")
print(f"  hit_rate: {baseline_scores['hit_rate']:.3f}")
print(f"  mrr:      {baseline_scores['mrr']:.3f}")

BASELINE — BAAI/bge-small-en-v1.5, off the shelf
  60 held-out questions, top_k=5
  hit_rate: 0.583
  mrr:      0.421

**What just happened?** A number to beat, produced by the same functions that will judge the fine-tuned model, on the same questions, against the same index of held-out chunks (**your values will differ** — the questions are freshly generated on your first run). Hit rate says whether the gold chunk came back at all; MRR says how near the top it landed. Fine-tuning is supposed to move the second one, which is exactly why we record both.

## 7. Training with `MultipleNegativesRankingLoss`

### Why this loss

A retriever has one job: put the right chunk closest to the question. Teaching that classically needs **triplets** — (question, right chunk, *wrong* chunk) — and somebody has to produce the wrong chunks. Mining good negatives is the expensive, fiddly part of embedding training.

`MultipleNegativesRankingLoss` (MNRL) sidesteps it. Feed it only **positive pairs**, `(anchor, positive)`, and it treats *every other positive in the same batch* as a negative for your anchor. A batch of 32 pairs becomes 32 little 32-way problems: "given this question, which of these 32 chunks is yours?" — cross-entropy over the in-batch cosine similarities.

That is the retrieval task's own shape: a ranking over candidates, not a yes/no judgement about one pair. Which is why MNRL is the default loss for training retrievers, and why our synthetic (question, chunk) pairs are all the supervision required.

### Why batch size is a *quality* knob here

For most losses batch size trades memory against speed. For MNRL it also sets **how hard the problem is**: batch size 8 means picking the right chunk out of 8; batch size 64 means picking it out of 64. Bigger batches mean a harder contrast and a sharper gradient, so MNRL is one of the few places where "as large as your hardware allows" is genuine advice about *quality*, not just throughput.

The trick has a matching hazard: because the other rows of the batch are *assumed* to be negatives, two near-duplicate chunks landing in one batch teach the model to push apart two things that belong together. `BatchSamplers.NO_DUPLICATES` is the cheap guard against the obvious version of that.

In [9]:
import contextlib

from datasets import Dataset
from sentence_transformers import SentenceTransformerTrainer, SentenceTransformerTrainingArguments
from sentence_transformers.sentence_transformer.losses import (
    CachedMultipleNegativesRankingLoss,
    MultipleNegativesRankingLoss,
)
from sentence_transformers.sentence_transformer.training_args import BatchSamplers

OUTPUT_DIR = "bge-small-ai-tutor-finetuned"

# MNRL wants exactly two columns: the anchor (the question) and its positive (the
# chunk that answers it). Negatives are the OTHER rows of each batch — nothing to
# mine, nothing to label.
chunk_text = {r["id"]: r["text"] for r in train_records}
train_dataset = Dataset.from_dict({
    "anchor": [p["question"] for p in train_pairs],
    "positive": [chunk_text[p["chunk_id"]] for p in train_pairs],
})

if DEVICE == "mps" and not hasattr(torch.mps, "device"):

    @contextlib.contextmanager
    def _mps_device(device=None):
        yield

    torch.mps.device = _mps_device

# A FRESH copy of the base weights — the trainer updates the model in place, and
# base_model from Section 6 must stay untouched to remain the "before".
model = SentenceTransformer(
    BASE_MODEL,
    device=DEVICE,
    model_kwargs={"attn_implementation": "eager"} if DEVICE == "mps" else None,
)
model.max_seq_length = MAX_SEQ_LEN

# MNRL embeds all 64 sequences at once and keeps every activation for the
# backward pass. The Cached variant (GradCache) walks the batch in slices of
# MINI_BATCH_SIZE and recomputes activations when the gradients need them, so
# the SAME 32 in-batch negatives fit in ~3 GB instead of ~20. It costs time, and
# its gradients match the uncached loss to ~1e-6 — so a GPU has no reason to pay.
if DEVICE == "cuda":
    loss = MultipleNegativesRankingLoss(model)
else:
    loss = CachedMultipleNegativesRankingLoss(model, mini_batch_size=MINI_BATCH_SIZE)

args = SentenceTransformerTrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,  # = how many in-batch negatives per anchor
    learning_rate=2e-5,  # small: we are nudging pre-trained weights, not training from scratch
    warmup_steps=0.1,  # float = ratio of total steps (warmup_ratio is deprecated in Transformers v5)
    fp16=torch.cuda.is_available(),  # half precision only where it is supported
    dataloader_pin_memory=torch.cuda.is_available(),  # pinned memory is a CUDA-only win; MPS/CPU warn otherwise
    batch_sampler=BatchSamplers.NO_DUPLICATES,  # keep near-duplicates out of one batch
    logging_steps=10,
    report_to=[],  # no experiment-tracker callbacks in a course notebook
)

trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    loss=loss,
)
trainer.train()

model.save_pretrained(OUTPUT_DIR)
print(f"\nFine-tuned model written to {OUTPUT_DIR}/ — {len(train_dataset)} pairs, {EPOCHS} epochs, batch {BATCH_SIZE}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-tuned model written to bge-small-ai-tutor-finetuned/ — 250 pairs, 3 epochs, batch 32

**What just happened?** Every weight in the encoder moved — this is a full fine-tune, not an adapter bolted onto frozen weights — and the falling loss you watched is the model getting better at picking the right chunk out of each batch of candidates. The result is a normal `sentence-transformers` model on disk: `SentenceTransformer("bge-small-ai-tutor-finetuned")` loads it anywhere, and it takes the same `(texts, task=...)` seam as every other embedder in the course.

Two operational consequences arrive with it. The artifact must be **versioned** alongside the index it built, and any retrain means **re-embedding the whole corpus** — old and new vectors live in unrelated spaces.

## 8. Before and After: Same Split, Same Functions

The comparison only counts if nothing else moved. Same held-out chunks, same held-out questions, same `hit_rate()` and `mrr()`, same `top_k`. The only difference is which weights turned text into vectors — so the fine-tuned model gets its **own** collection, because its vectors are not comparable with the base model's.

The table below is computed, not typed. Whatever it prints on your run is the result.

In [10]:
import pandas as pd

# Load the SAVED model from disk — the artifact you would actually ship, not the
# object still sitting in memory from the training cell.
tuned_model = SentenceTransformer(OUTPUT_DIR, device=DEVICE)
tuned_embed = embedder_for(tuned_model)

# A fresh collection: two models, two vector spaces, never one index.
tuned_collection = get_collection("finetune_tuned")
index_chunks(test_records, tuned_collection, embed_fn=tuned_embed)

tuned_retriever = retriever_for(tuned_collection, tuned_embed)
tuned_scores = {
    "hit_rate": hit_rate(test_pairs, tuned_retriever, top_k=TOP_K),
    "mrr": mrr(test_pairs, tuned_retriever, top_k=TOP_K),
}

before_after = pd.DataFrame([
    {"model": f"{BASE_MODEL} (off the shelf)", **baseline_scores},
    {"model": f"{BASE_MODEL} (fine-tuned)", **tuned_scores},
    {
        "model": "difference",
        "hit_rate": tuned_scores["hit_rate"] - baseline_scores["hit_rate"],
        "mrr": tuned_scores["mrr"] - baseline_scores["mrr"],
    },
]).round(3)

print(f"{len(test_pairs)} held-out questions | top_k={TOP_K} | identical chunks, identical questions")
before_after

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

60 held-out questions | top_k=5 | identical chunks, identical questions

                                    model  hit_rate    mrr
0  BAAI/bge-small-en-v1.5 (off the shelf)     0.583  0.421
1     BAAI/bge-small-en-v1.5 (fine-tuned)     0.633  0.493
2                              difference     0.050  0.072

**What just happened?** One table, produced entirely by the code above, answers the only question this notebook exists to ask: did training the encoder on your own (question, chunk) pairs make retrieval better on documents it never saw? Read the `difference` row rather than the absolute values, and read MRR at least as carefully as hit rate — moving the gold chunk *up* is the gain that actually reaches the generator (**your numbers will differ**; questions, split, and training run are all regenerated on your machine).

Two caveats that keep you honest. With a test set this small, a difference of one or two points is **noise, not signal** — raise `N_TEST_PAIRS` before making a decision on this evidence. And the training questions were written by an LLM reading the chunks, so the model is partly learning *that generator's* idea of a question; the day you have real user queries, retrain on those and measure again.