<a href="https://colab.research.google.com/github/towardsai/ai-tutor-rag-system/blob/main/notebooks/15-Use_OpenSource_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Open-Weight Models via Together AI: One `provider` Away

Every model this course has called so far is proprietary and closed. Open-weight models — Llama, Qwen, gpt-oss and friends — ship their weights publicly, run on hosts that compete on price, and can later move onto hardware you control. The question this notebook answers is a practical one: **how much of your code changes when you swap the model that writes the answer?**

The answer is one argument. `generate()` and `answer()` take a `provider=`, a one-line `BASE_URLS` table holds Together's OpenAI-compatible endpoint, and the retrieval pipeline never learns that anything changed.

📎 *Every pipeline and evaluation function in this notebook is the same plain-Python code you built across Sections 3–4 — redefined right here, in full view. No framework, no course package.*

## 🧭 What You'll Learn

- Why **OpenAI-compatible** endpoints are the lingua franca of model hosting, and what a `base_url` actually swaps
- Running the full course RAG pipeline with an open-weight model doing the answering — same retrieval, same prompt
- Comparing two models on **identical retrieved context**, which is the only fair comparison
- Turning "which one is better?" into a **faithfulness rate** with the course's typed judges
- What open weights buy you (price, portability, control) and what the licenses actually say

## 1. Setup: Environment, Keys, and Providers

The usual setup cell, with one extra key (`TOGETHER_API_KEY`, free credits at [together.ai](https://www.together.ai/)) and one extra picker: the open model to serve. All three model fields are editable — type any ID from Together's catalog.

In [1]:
# ============================================================
# ⚙️ Setup — environment, dependencies, API keys, provider
# ============================================================
import os
import sys

IN_COLAB = "google.colab" in sys.modules

# Pick your model providers (dropdowns in Colab; edit the values locally)
PROVIDER = "gemini"  # @param ["gemini", "openai", "anthropic"]
EMBED_PROVIDER = "gemini"  # @param ["gemini", "openai"]  (Anthropic has no embedding API)

# Pick a model for the selected provider — or TYPE any newer model ID into the
# box (the dropdown is editable thanks to allow-input):
CHAT_MODEL = "gemini-3.7-flash"  # @param ["gemini-3.7-flash", "gemini-3.5-flash-lite", "gpt-5.6-luna", "claude-sonnet-5"] {allow-input: true}
EMBED_MODEL = "gemini-embedding-001"  # @param ["gemini-embedding-001", "text-embedding-3-small"] {allow-input: true}

# The open model served by Together — pick one or TYPE any model ID from their catalog
OPEN_MODEL = "MiniMaxAI/MiniMax-M3"  # @param ["meta-llama/Llama-4-Scout-17B-16E-Instruct", "openai/gpt-oss-20b"] {allow-input: true}

_KEY_FOR = {"gemini": "GOOGLE_API_KEY", "openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}
REQUIRED_KEYS = sorted({_KEY_FOR[PROVIDER], _KEY_FOR[EMBED_PROVIDER]}) + ["TOGETHER_API_KEY"]

if IN_COLAB:
    import importlib
    import site
    import subprocess

    # Shared install profile, pinned course-wide (July 2026). Note what is NOT
    # here: no Together SDK — an OpenAI-compatible host needs no extra package.
    subprocess.run(
        [
            sys.executable, "-m", "pip", "install", "-q", "-U",
            "google-genai==2.3.0",
            "openai==2.46.0",
            "anthropic==0.117.0",
            "chromadb==1.5.9",
            "tiktoken==0.13.0",
        ],
        check=True,
    )
    importlib.reload(site)  # make newly installed packages importable without a runtime restart

    # In Colab: Secrets tab (🔑 icon) → Add new secret → e.g. TOGETHER_API_KEY
    from google.colab import userdata

    for key in REQUIRED_KEYS:
        os.environ[key] = userdata.get(key)

if not IN_COLAB:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")

    # Locally: dependencies are installed once from the repo's requirements.
    # Keys live in a .env file at the repo root.
    from dotenv import load_dotenv

    load_dotenv()
    missing = [k for k in REQUIRED_KEYS if not os.getenv(k)]
    assert not missing, f"Missing from .env: {missing}"

print(f"✅ Setup complete — {'Colab' if IN_COLAB else 'local'} | chat: {PROVIDER} | embeddings: {EMBED_PROVIDER} | open model: {OPEN_MODEL}")

✅ Setup complete — local | chat: gemini | embeddings: gemini | open model: MiniMaxAI/MiniMax-M3

## 2. The Pipeline, Redefined in Plain Python

The helpers below are the same ones as the rest of Sections 4–5, pasted in full so this notebook stands alone. Note what is *not* here: no second client class, no Together SDK, no open-model-specific wrapper — and no course package either. The one addition over previous notebooks: `generate()` learns a `provider=` override for OpenAI-compatible hosts.

In [2]:
# 📎 generate() and embed() — the two course helpers, exactly as built in
#    "How To Use LLMs via API" and "Basic RAG", with ONE addition for this
#    lesson: generate() can reach any OpenAI-compatible host (Together,
#    DeepSeek, a local Ollama server…) via provider= / base_url= overrides.
from anthropic import Anthropic
from google import genai
from google.genai import types as genai_types
from openai import OpenAI

# Course-standard default models per provider (August 2026)
MODELS = {
    "gemini": "gemini-3.7-flash",
    "openai": "gpt-5.6-luna",
    "anthropic": "claude-sonnet-5",
}

# The setup-cell form selection (or any typed model ID) overrides the default:
MODELS[PROVIDER] = CHAT_MODEL
EMBED_MODELS = {
    "gemini": "gemini-embedding-001",
    "openai": "text-embedding-3-small",
}
EMBED_MODELS[EMBED_PROVIDER] = EMBED_MODEL  # setup-cell selection (or typed ID) wins
EMBED_DIM = 1536  # same output size for both providers, so the rest of the code never cares

# Every OpenAI-compatible host we might call, in ONE table. Adding a host is
# adding a line — that is the entire "integration".
BASE_URLS = {
    "together": "https://api.together.ai/v1",
    "deepseek": "https://api.deepseek.com/v1",
    "ollama": "http://localhost:11434/v1",  # local server; no API key needed
}

# Create only the clients we actually need
if "gemini" in (PROVIDER, EMBED_PROVIDER):
    gemini_client = genai.Client()
if "openai" in (PROVIDER, EMBED_PROVIDER):
    openai_client = OpenAI()
if PROVIDER == "anthropic":
    anthropic_client = Anthropic()


def generate(prompt, system=None, model=None, provider=None, base_url=None, api_key=None):
    """Send one prompt to a model and return the reply text.

    With no extra arguments this is the same generate() as every previous
    notebook: it uses the globally selected PROVIDER. Pass provider= (a name
    from BASE_URLS) or base_url= to reach an OpenAI-compatible host instead.
    Overrides are per-call — they never touch the module-level defaults.
    """
    provider = provider or PROVIDER

    if provider not in ("gemini", "openai", "anthropic"):
        # Any OpenAI-compatible host: the OFFICIAL openai SDK, different URL.
        # These hosts speak the classic chat.completions endpoint (not the
        # newer Responses API), so the reply is at choices[0].message.content.
        url = base_url or BASE_URLS[provider]
        key = api_key or os.environ.get(f"{provider.upper()}_API_KEY", "ollama")
        client = OpenAI(base_url=url, api_key=key)
        messages = ([{"role": "system", "content": system}] if system else []) + [
            {"role": "user", "content": prompt}
        ]
        response = client.chat.completions.create(
            model=model or OPEN_MODEL, messages=messages
        )
        return response.choices[0].message.content

    if provider != PROVIDER:
        raise ValueError(
            "Switching between the three native providers happens in the setup "
            "cell (the PROVIDER dropdown); per-call provider= is for "
            "OpenAI-compatible hosts like 'together'."
        )

    if provider == "gemini":
        response = gemini_client.models.generate_content(
            model=model or MODELS["gemini"],
            contents=prompt,
            config=genai_types.GenerateContentConfig(system_instruction=system),
        )
        return response.text

    if provider == "openai":
        response = openai_client.responses.create(
            model=model or MODELS["openai"],
            instructions=system,
            input=prompt,
            reasoning={"effort": "none"},
        )
        return response.output_text

    if provider == "anthropic":
        response = anthropic_client.messages.create(
            model=model or MODELS["anthropic"],
            max_tokens=4096,
            **({"system": system} if system else {}),
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    raise ValueError(f"Unknown PROVIDER: {PROVIDER!r}")


def embed(texts, task="document"):
    """Embed a list of texts with the selected EMBED_PROVIDER.

    Returns a list of EMBED_DIM-dimensional vectors (one per input text).
    task: "document" for corpus chunks, "query" for user questions —
    Gemini embeds the two slightly differently to improve retrieval.
    """
    if isinstance(texts, str):
        texts = [texts]
    # Embedding models work best on single-line inputs
    texts = [t.replace("\n", " ") for t in texts]

    if EMBED_PROVIDER == "gemini":
        result = gemini_client.models.embed_content(
            model=EMBED_MODELS["gemini"],
            contents=texts,
            config=genai_types.EmbedContentConfig(
                task_type="RETRIEVAL_DOCUMENT" if task == "document" else "RETRIEVAL_QUERY",
                output_dimensionality=EMBED_DIM,
            ),
        )
        return [e.values for e in result.embeddings]

    if EMBED_PROVIDER == "openai":
        result = openai_client.embeddings.create(
            model=EMBED_MODELS["openai"], input=texts
        )
        return [d.embedding for d in result.data]

    raise ValueError(f"Unknown EMBED_PROVIDER: {EMBED_PROVIDER!r}")

## 3. The `provider` Argument — and What It Hides

Together's API is compatible with the OpenAI REST API, so reaching it needs no new client library: it is the *official `openai` SDK* pointed at a different URL. Our `generate()` keeps that URL in one table (`BASE_URLS`) alongside DeepSeek and a local Ollama server, so calling an open model is `provider="together"`.

One nuance worth knowing: compatible hosts implement the classic **`chat.completions`** endpoint (not OpenAI's newer Responses API), so the reply text arrives at `choices[0].message.content`. The branch is right above in `generate()` — read it; it is a dozen lines.

In [3]:
print(generate(
    "In one sentence, who trained you and what model are you?",
    provider="together",
    model=OPEN_MODEL,
))

I am MiniMax-M3, an AI model developed and trained by MiniMax, a global AI foundation model company founded in early 2022.

**What just happened?** No new SDK, no new client object, no new function name — one keyword argument put an open-weight model behind the exact call the course has used since Section 1. Per-call overrides never touch the module-level defaults either, which is what makes the side-by-side comparison later in this notebook honest.

The mechanism, stripped of even our own helper, is three lines:

```python
from openai import OpenAI
client = OpenAI(base_url="https://api.together.ai/v1", api_key=os.environ["TOGETHER_API_KEY"])
client.chat.completions.create(model=OPEN_MODEL, messages=[...]).choices[0].message.content
```

## 4. Rebuild the Knowledge Base

📎 *Everything here is verbatim from Sections 3–4: the corpus download, `chunk()`, `ingest()` into the persistent Chroma collection, and `search()`. Same chunker, same stable `{title[:40]}-{i}` ids, same collection — so if an earlier notebook already built the knowledge base in this folder, `ingest()` upserts the same records and nothing is stored twice.*

In [4]:
import csv
import pathlib

import requests

# Course dataset — hosted in the Towards AI org dataset repo on Hugging Face
DATA_URL = "https://huggingface.co/datasets/towardsai-tutors/full-stack-ai-engineering-data/resolve/main/ai-docs.csv"
DATA_PATH = pathlib.Path("ai-docs.csv")

if not DATA_PATH.exists():
    DATA_PATH.write_bytes(requests.get(DATA_URL, timeout=30).content)
    print("Downloaded", DATA_PATH)

# Read the articles WITH their metadata (title, url, source) — we carry it everywhere
articles = []
with open(DATA_PATH, mode="r", encoding="utf-8") as f:
    for idx, row in enumerate(csv.reader(f)):
        if idx == 0:
            continue  # skip the header row
        articles.append({"title": row[0], "text": row[1], "url": row[2], "source": row[3]})

print(f"{len(articles)} articles loaded")

23 articles loaded

In [5]:
import chromadb
import tiktoken

# 📎 chunk() and n_tokens() from "From Script to Pipeline"
ENC = tiktoken.get_encoding("cl100k_base")


def n_tokens(text):
    """Number of tokens in a string."""
    return len(ENC.encode(text))


def chunk(text, chunk_size=512, chunk_overlap=128):
    """Split text into token-based chunks; consecutive chunks share chunk_overlap tokens."""
    tokens = ENC.encode(text)
    chunks = []
    step = chunk_size - chunk_overlap
    for start in range(0, len(tokens), step):
        window = tokens[start : start + chunk_size]
        chunks.append(ENC.decode(window))
        if start + chunk_size >= len(tokens):
            break  # the final window reached the end of the text
    return chunks


# Same Chroma directory AND collection as Section 4 — same chunker, same stable ids.
chroma_client = chromadb.PersistentClient(path="./ai-docs-chroma")
collection = chroma_client.get_or_create_collection(
    name="ai-docs",
    metadata={"hnsw:space": "cosine"},  # distance = 1 - cosine similarity
)


# 📎 ingest() from "Improving Data Sources and Prompts" — idempotent by stable ids
def ingest(articles, collection, chunk_size=512, chunk_overlap=128, batch_size=50):
    records = []
    for art in articles:
        for i, piece in enumerate(chunk(art["text"], chunk_size, chunk_overlap)):
            records.append({
                "id": f"{art['title'][:40]}-{i}",
                "text": piece,
                "title": art["title"],
                "url": art["url"],
                "source": art["source"],
            })
    for start in range(0, len(records), batch_size):
        batch = records[start : start + batch_size]
        collection.upsert(
            ids=[r["id"] for r in batch],
            documents=[r["text"] for r in batch],
            embeddings=embed([r["text"] for r in batch], task="document"),
            metadatas=[{"title": r["title"], "url": r["url"], "source": r["source"]} for r in batch],
        )
    return len(records)


n = ingest(articles, collection)
print(f"Knowledge base ready: {collection.count()} chunks")


# 📎 search() from the evaluation lesson — the collection passed explicitly here
def search(query, collection, top_k=5):
    result = collection.query(
        query_embeddings=[embed(query, task="query")[0]], n_results=top_k
    )
    return [
        {"id": cid, "text": doc, "score": 1 - dist, **meta}
        for cid, doc, dist, meta in zip(
            result["ids"][0], result["documents"][0],
            result["distances"][0], result["metadatas"][0],
        )
    ]

Knowledge base ready: 233 chunks

## 5. RAG with the Open Model

Same retrieval, same course prompt — only the model that writes the final answer changes. `answer()` takes the same `provider`/`model` overrides `generate()` does, so the whole pipeline switches with two keywords.

In [6]:
# The course RAG prompt and system instruction — the same constants as every
# notebook since RAG 101. Print them, diff them, edit them: they are yours.
SYSTEM_INSTRUCTION = (
    "You are an assistant and expert in answering questions from a chunks of content. "
    "Only answer AI-related question, else say that you cannot answer this question."
)

PROMPT_TEMPLATE = (
    "Read the following informations that might contain the context you require to "
    "answer the question. You can use the informations starting from the "
    "<START_OF_CONTEXT> tag and end with the <END_OF_CONTEXT> tag. Here is the content:\n\n"
    "<START_OF_CONTEXT>\n{context}\n<END_OF_CONTEXT>\n\n"
    "Please provide an informative and accurate answer to the following question based "
    "on the available context. Be concise and take your time.\nQuestion: {question}\nAnswer:"
)


# 📎 answer() from "From Script to Pipeline" — plus the same provider/model
#    overrides generate() takes, passed straight through.
def answer(question, collection, top_k=5, **overrides):
    """The whole pipeline in one call: search, then grounded generation."""
    retrieved = search(question, collection, top_k=top_k)
    context = "\n\n".join(r["text"] for r in retrieved)
    reply = generate(
        PROMPT_TEMPLATE.format(context=context, question=question),
        system=SYSTEM_INSTRUCTION,
        **overrides,
    )
    return reply, retrieved


def show_answer(reply, retrieved):
    """Print an answer with the chunks (and scores) that grounded it."""
    print(reply)
    print("\n--- sources ---")
    for r in retrieved:
        print(f"  {r['score']:.4f} | {r['title'][:60]}")


reply, retrieved = answer(
    "How many parameters does the Qwen3.8 model have?",
    collection,
    top_k=5,
    provider="together",
    model=OPEN_MODEL,
)

show_answer(reply, retrieved)

Based on the provided context, the Qwen3.8 model has:

- **Total Parameters:** 2.4T (2.4 trillion)
- **Activated Parameters:** 95B (95 billion)

This is a Mixture of Experts (MoE) architecture, which is why the activated parameter count is significantly lower than the total parameter count. The model has 512 experts in total, with 10 routed experts + 1 shared expert activated per token.

--- sources ---
  0.7828 | Qwen3.8-2.4T-A95B Model Card
  0.7407 | Qwen3.8-2.4T-A95B Model Card
  0.7299 | Qwen3.8-2.4T-A95B Model Card
  0.7217 | Qwen3.8-2.4T-A95B Model Card
  0.6970 | Kimi K3 Model Card

**What just happened?** Retrieval, prompt construction, and source tracking ran exactly as before; the open model only did the last step. That is the payoff of building the pipeline as plain functions with a model seam: the *choice* of model is a keyword, not a refactor.

## 6. Side by Side: Open vs. Course Default

Comparing two models means holding everything else fixed — including the retrieved chunks. Retrieve **once**, build **one** prompt, send it to **two** models. (Calling `answer()` twice would retrieve twice; identical in practice, but "in practice" is not a controlled comparison.)

In [7]:
question = "What is special about the Qwen3.8 model's architecture?"

hits = search(question, collection, top_k=5)                        # retrieve ONCE
context = "\n\n".join(r["text"] for r in hits)
prompt = PROMPT_TEMPLATE.format(context=context, question=question)  # ONE prompt

print(f"### Course default ({CHAT_MODEL}) ###\n")
print(generate(prompt, system=SYSTEM_INSTRUCTION))

print(f"\n### Open model ({OPEN_MODEL}) ###\n")
print(generate(prompt, system=SYSTEM_INSTRUCTION, provider="together", model=OPEN_MODEL))

### Course default (gemini-3.7-flash) ###

Based on the provided context, the key architectural features of the Qwen3.8 model (Qwen3.8-2.4T-A95B) include:

* **Parameter & MoE Configuration:** It features a total of **2.4 trillion parameters** with **95 billion activated** parameters, using a Mixture of Experts (MoE) setup with 512 total experts (10 routed + 1 shared).
* **Hybrid Hidden Layout:** It contains 92 layers arranged in a specialized repeating layout:
  `23 × (3 × (Gated DeltaNet → MoE) → 1 × (Gated Attention → MoE))`
* **Dual Attention Mechanism:** It alternates between **Gated DeltaNet** (linear attention with 128 V heads and 16 QK heads) and **Gated Attention** (64 Q heads and 4 KV heads).
* **Multi-Token Prediction (MTP):** It is trained using multi-step Multi-Token Prediction.
* **Context Capacity:** It supports a native context length of **262,144 tokens**, which is extensible up to **1,010,000 tokens**.

### Open model (MiniMaxAI/MiniMax-M3) ###

Based on the provided context, the Qwen3.8 model has several distinctive architectural features:

1. **Massive Sparse Mixture-of-Experts (MoE) Design**: The model has a total of **2.4 trillion parameters**, but only **95 billion are activated** during inference, using 512 experts with 10 routed + 1 shared activated experts per token.

2. **Hybrid Linear/Full Attention Architecture**: It uses a unique interleaved hidden layout of `23 × (3 × (Gated DeltaNet → MoE) → 1 × (Gated Attention → MoE))`, combining:
   - **Gated DeltaNet** (linear attention): 128 heads for V and 16 heads for QK with head dimension 128
   - **Gated Attention** (standard attention): 64 heads for Q and 4 heads for KV (grouped-query style) with head dimension 256

   This creates a 3:1 ratio of linear-attention to full-attention blocks, balancing efficiency with full-attention quality.

3. **Multi-Token Prediction (MTP)**: Trained with multiple steps of MTP, which improves training efficiency and downstream performance.

4. **Ultra-Long Context Support**: Native context length of **262,144 tokens**, extensible up to **1,010,000 tokens** (over 1M).

5. **Deep & Wide Design**: 92 layers with hidden dimension 8192 and a token embedding vocabulary of 248,320.

The combination of the **hybrid DeltaNet + full-attention MoE architecture** with such a large total parameter count (2.4T) while only activating ~95B parameters is the most distinctive architectural choice, enabling both strong performance and efficient inference.

**What just happened?** Two models, one context, one prompt. Differences you see now are the models', not the retriever's. This is also a small lesson in prompt ownership: `PROMPT_TEMPLATE` and `SYSTEM_INSTRUCTION` are constants you can print, diff, and edit — read them before you blame a model.

## 7. Measure It: the Faithfulness Judge

📎 *The typed judges from the RAG-evaluation lesson, redefined below unchanged.* Comparing answers by eye doesn't scale; a faithfulness rate over a handful of questions is a real (if small-sample) signal of whether the open model stays grounded in the retrieved context.

Note which model judges: the judge functions call `generate()` with **no provider override**, so the open model is being graded *by* the course default — not by itself.

In [8]:
# 📎 The typed judges from "Evaluating Your RAG Pipeline" — verbatim.
from pydantic import BaseModel

JUDGE_SYSTEM = "You are a strict evaluator. Respond with ONLY the requested JSON object — no prose, no code fences."


class FaithfulnessVerdict(BaseModel):
    faithful: bool
    reason: str


class RelevancyVerdict(BaseModel):
    relevant: bool
    reason: str


FAITHFULNESS_PROMPT = """Judge whether the ANSWER is fully supported by the CONTEXT.
If any claim in the answer is not backed by the context, it is not faithful.

CONTEXT:
{context}

ANSWER:
{answer}

Return ONLY JSON: {{"faithful": true or false, "reason": "<one sentence>"}}"""

RELEVANCY_PROMPT = """Judge whether the ANSWER (built from the CONTEXT) actually addresses the QUESTION.

QUESTION:
{question}

CONTEXT:
{context}

ANSWER:
{answer}

Return ONLY JSON: {{"relevant": true or false, "reason": "<one sentence>"}}"""


def _clean(raw):
    return raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()


def judge_faithfulness(answer_text, context):
    raw = generate(FAITHFULNESS_PROMPT.format(context=context, answer=answer_text), system=JUDGE_SYSTEM)
    return FaithfulnessVerdict.model_validate_json(_clean(raw))


def judge_relevancy(question, answer_text, context):
    raw = generate(RELEVANCY_PROMPT.format(question=question, context=context, answer=answer_text), system=JUDGE_SYSTEM)
    return RelevancyVerdict.model_validate_json(_clean(raw))

In [9]:
import pandas as pd

QUESTIONS = [
    "How many parameters does the Qwen3.8 model have?",
    "What is special about the Qwen3.8 model's architecture?",
    "What context length does Qwen3.8 support?",
    "Under what license are the GLM-5.2 model weights released?",
    "What are the three models in the GPT-5.6 family?",
]

rows = []
for label, overrides in [
    (f"course default ({CHAT_MODEL})", {}),
    (f"open ({OPEN_MODEL})", {"provider": "together", "model": OPEN_MODEL}),
]:
    n_faithful = n_relevant = 0
    for q in QUESTIONS:
        reply, retrieved = answer(q, collection, top_k=5, **overrides)
        context = "\n\n".join(r["text"] for r in retrieved)
        n_faithful += judge_faithfulness(reply, context).faithful
        n_relevant += judge_relevancy(q, reply, context).relevant
    rows.append({
        "model": label,
        "faithfulness": n_faithful / len(QUESTIONS),
        "relevancy": n_relevant / len(QUESTIONS),
    })

pd.DataFrame(rows)

                               model  faithfulness  relevancy
0  course default (gemini-3.7-flash)           1.0        1.0
1        open (MiniMaxAI/MiniMax-M3)           1.0        1.0

**What just happened?** The open model's grounding got a number, produced by the same judge functions the course uses everywhere — evaluation code is provider-neutral too. Five questions is a *sniff test*, not a verdict: for a real comparison, run the full QA dataset from the evaluation lesson at matched top-k and add the correctness judge where references exist. And inspect the failures — print a failing verdict's `.reason` and the judge names what it objected to.

## 8. Price the Difference

The economic argument for open weights is per-token price, and a RAG query is mostly *input* tokens — the retrieved context dominates. So the saving is real and computable: `n_tokens()` measures what a query actually sends, and a small `estimate_cost()` prices it against a **dated table defined right below** (`MODEL_PRICES`, as of July 2026 — check the linked pricing pages before quoting these numbers).

In [10]:
QUERIES_PER_MONTH = 100_000
OUTPUT_TOKENS = 400  # a typical grounded answer

# USD per 1M tokens (input, output) — **as of August 2026**, from the providers'
# pricing pages (ai.google.dev/pricing, together.ai/pricing). Update before quoting.
MODEL_PRICES = {
    "gemini-3.7-flash": (0.75, 3.75),  # introductory through Dec 31, 2026 — then (1.50, 7.50)
    "meta-llama/Llama-4-Scout-17B-16E-Instruct": (0.08, 0.30),
    # Add the model you picked, from its host's pricing page:
    # "your/model-id": (input_per_M, output_per_M),
}


def estimate_cost(input_tokens, output_tokens, model):
    """USD for one call at MODEL_PRICES — or None if the model isn't in the table.

    None is a feature: an unpriced model reads "not priced", never a made-up number.
    """
    if model not in MODEL_PRICES:
        return None
    price_in, price_out = MODEL_PRICES[model]
    return input_tokens * price_in / 1e6 + output_tokens * price_out / 1e6


hits = search("What is special about the Qwen3.8 model's architecture?", collection, top_k=5)
prompt_tokens = n_tokens("\n\n".join(r["text"] for r in hits)) + 200  # context + question + instructions

rows = []
for label, model in [("course default", CHAT_MODEL), ("open (Together)", OPEN_MODEL)]:
    per_query = estimate_cost(prompt_tokens, OUTPUT_TOKENS, model=model)
    rows.append({
        "model": f"{label}: {model}",
        "prompt tokens": prompt_tokens,
        "$/query": f"{per_query:.5f}" if per_query is not None else "not priced",
        f"$/{QUERIES_PER_MONTH:,} queries": f"{per_query * QUERIES_PER_MONTH:,.0f}" if per_query else "—",
    })

pd.DataFrame(rows)

,model,prompt tokens,$/query,"$/100,000 queries"
0,course default: gemini-3.7-flash,2651,0.00349,349
1,open (Together): MiniMaxAI/MiniMax-M3,2651,not priced,—

**What just happened?** The same query, priced twice. `estimate_cost` returns `None` rather than a wrong number for any model missing from the table — so if you type a model ID into the picker that `MODEL_PRICES` doesn't cover, you get "not priced", never a fabricated figure. (That includes the default pick if you haven't added it yet — grab the current price from Together's pricing page and add one line.) At a hundred thousand queries a month the gap stops being academic; at a hundred a month it is noise, and you should optimise for quality instead. That is the whole decision, and now it is arithmetic.

## 9. What "Open" Buys You — and What It Costs

Three facts to keep straight (all **as of August 2026 — verify before relying on them**):

- **Licenses**: Llama 4 ships under Meta's *community license* — free for most commercial use, but with conditions (notably restrictions for companies above 700M monthly users). "Open **weights**" is the accurate term; it is not OSI open source. `openai/gpt-oss-20b` and the Qwen family ship under Apache-2.0, which is. Every open model has its own license — read it.
- **Prices**: the table above is the argument — Llama 4 Scout serves around **$0.08 / 1M input and $0.30 / 1M output** on major hosts, against $0.75/$3.75 (introductory Gemini 3.7 Flash rates — $1.50/$7.50 from January 2027) for the course-default Gemini model. Check [Together's pricing page](https://www.together.ai/pricing) for current numbers, and update `MODEL_PRICES` when they move.
- **Control**: the same weights can later move on-premises — an option no proprietary API offers. `generate(..., provider="ollama")` points the identical code at `localhost`, which is the whole portability argument in one line. The trade-off is that you now operate a model.

The pipeline lesson stands: because everything runs behind `generate()`-shaped functions, the *choice* of model — proprietary, hosted open, or local — is a one-keyword decision you can revisit with data instead of dogma.

## 10. 🔬 Optional Experiment: Same Code, Three Hosts

`provider=` accepts any host in the `BASE_URLS` table, and `base_url=` covers the ones that aren't in it. Everything below is the same `generate()` call.

In [11]:
# 🔬 OPTIONAL EXPERIMENT — each line needs that provider's key in your environment.
#
# generate("Say hi in five words.", provider="deepseek")                   # DEEPSEEK_API_KEY
# generate("Say hi in five words.", provider="ollama", model="llama3.2")   # no key: localhost
# generate("Say hi in five words.", provider="fireworks",                  # any OpenAI-compatible host
#          base_url="https://api.fireworks.ai/inference/v1",
#          model="accounts/fireworks/models/llama4-scout-instruct-basic",
#          api_key=os.environ.get("FIREWORKS_API_KEY"))

## 🔑 Key Takeaways

- **OpenAI-compatible is the lingua franca**: the official `openai` SDK plus a different `base_url` reaches Together, Fireworks, Groq, DeepSeek, or your own vLLM/Ollama server — no new client code. Our `generate()` keeps those URLs in one table (`BASE_URLS`) so it becomes `provider="together"`.
- Compatible hosts speak `chat.completions`, so replies arrive at `choices[0].message.content` — worth knowing even when a helper hides it.
- The course pipeline needed **zero changes** to swap the answering model: retrieval, prompts, and judges are provider-neutral by construction, and per-call overrides never mutate the module defaults.
- Compare models on **identical retrieved context** (retrieve once, prompt once, generate twice), then **measure** with the judges instead of trusting side-by-side vibes.
- Price the decision rather than asserting it: `n_tokens()` × `estimate_cost()` turns "cheaper" into dollars per hundred thousand queries — and returns `None` instead of guessing for models it doesn't price.
- "Open" means open *weights* under a specific license, at per-token prices several times below frontier models, with the unique option of moving on-premises later.